import { StyleSheet } from 'react-native';
import { theme } from '../theme';

const styles = StyleSheet.create({
  card: {
    backgroundColor: theme.colors.bgSurface,
    borderColor: theme.colors.border,
    borderWidth: 1,
    borderRadius: 16,
    overflow: 'hidden',
    marginBottom: 14,
    shadowColor: theme.colors.shadow,
    shadowOpacity: 0.28,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 14 },
  },
  content: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 18,
    paddingBottom: 14,
  },
  eyebrowRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    minWidth: 0,
  },
  eyebrow: {
    color: theme.colors.textSecondary,
    fontFamily: theme.fonts.semibold,
    fontSize: 11,
    letterSpacing: 1.1,
    textTransform: 'uppercase',
    flex: 1,
    flexShrink: 1,
  },
  metricsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  metric: {
    color: theme.colors.textSecondary,
    fontFamily: theme.fonts.semibold,
    fontSize: 11,
  },
  heading: {
    color: theme.colors.textPrimary,
    fontFamily: theme.fonts.serif,
    fontSize: 29,
    lineHeight: 34,
    marginTop: 12,
    flexShrink: 1,
  },
  promptRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 10,
    minWidth: 0,
  },
  prompt: {
    color: theme.colors.textSecondary,
    fontFamily: theme.fonts.regular,
    fontSize: 13,
    fontStyle: 'italic',
    flex: 1,
    flexShrink: 1,
  },
  refreshButton: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderColor: theme.colors.border,
    borderWidth: 1,
    backgroundColor: theme.colors.bgRaised,
    alignItems: 'center',
    justifyContent: 'center',
  },
  refreshText: {
    color: theme.colors.textSecondary,
    fontFamily: theme.fonts.regular,
    fontSize: 13,
  },
  divider: {
    flex: 1,
    borderTopColor: theme.colors.border,
    borderTopWidth: 1,
    marginTop: 16,
    paddingTop: 12,
  },
  formatToolbar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 10,
    flexWrap: 'wrap',
  },
  postedScroll: {
    flex: 1,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.bgSurface,
    minHeight: 120,
  },
  postedScrollContent: {
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  input: {
    backgroundColor: theme.colors.bgSurface,
    color: theme.colors.textPrimary,
    fontFamily: theme.fonts.regular,
    fontSize: 16,
    lineHeight: 23,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: theme.colors.border,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  inputMultiline: {
    minHeight: 120,
    textAlignVertical: 'top',
  },
  postedText: {
    color: theme.colors.textPrimary,
    fontFamily: theme.fonts.regular,
    fontSize: 16,
    lineHeight: 23,
  },
  postedBlocks: {
    gap: 10,
  },
  postedTitle: {
    color: theme.colors.textPrimary,
    fontFamily: theme.fonts.serif,
    fontSize: 34,
    lineHeight: 40,
    marginBottom: 12,
  },
  postedQuoteBlock: {
    borderLeftWidth: 3,
    borderLeftColor: theme.colors.accent,
    paddingLeft: 10,
  },
  postedQuoteText: {
    color: theme.colors.textPrimary,
    fontStyle: 'italic',
    opacity: 0.82,
  },
  footer: {
    borderTopColor: theme.colors.border,
    borderTopWidth: 1,
    paddingHorizontal: 16,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    flexWrap: 'wrap',
  },
  footerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flex: 1,
    minWidth: 0,
    flexWrap: 'wrap',
  },
  remaining: {
    color: theme.colors.textSecondary,
    fontFamily: theme.fonts.regular,
    fontSize: 13,
  },
  visibilityButton: {
    borderColor: theme.colors.border,
    borderWidth: 1,
    borderRadius: 999,
    backgroundColor: theme.colors.bgRaised,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 5,
    paddingLeft: 6,
    paddingRight: 10,
    maxWidth: '100%',
  },
  toggleTrack: {
    width: 34,
    height: 18,
    borderRadius: 999,
    justifyContent: 'center',
  },
  toggleThumb: {
    width: 14,
    height: 14,
    borderRadius: 7,
  },
  visibilityText: {
    color: theme.colors.textPrimary,
    fontFamily: theme.fonts.semibold,
    fontSize: 12,
    flexShrink: 1,
  },
  button: {
    borderColor: theme.colors.border,
    borderWidth: 1,
    backgroundColor: 'transparent',
    borderRadius: 10,
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  buttonDisabled: {
    backgroundColor: theme.colors.white04,
  },
  buttonText: {
    color: theme.colors.textPrimary,
    fontFamily: theme.fonts.semibold,
    fontSize: 14,
    lineHeight: 16,
  },
  helperText: {
    color: theme.colors.textMuted,
    fontFamily: theme.fonts.regular,
    fontSize: 12,
    textAlign: 'right',
    marginTop: 10,
  },
  error: {
    color: theme.colors.danger,
    fontFamily: theme.fonts.regular,
    fontSize: 12,
    paddingHorizontal: 16,
    paddingBottom: 12,
  },
  formatButton: {
    borderColor: theme.colors.border,
    borderWidth: 1,
    borderRadius: 8,
    backgroundColor: theme.colors.bgRaised,
    width: 28,
    height: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  formatButtonWide: {
    width: 34,
  },
  formatButtonText: {
    color: theme.colors.textPrimary,
    fontFamily: theme.fonts.semibold,
    fontSize: 14,
    lineHeight: 16,
  },
  formatButtonTextUnderline: {
    textDecorationLine: 'underline',
  },
});

export default styles;
