import { StyleSheet } from 'react-native';
import { theme } from '../theme';

const styles = StyleSheet.create({
  outer: {
    zIndex: 20,
    backgroundColor: theme.colors.bgBase,
  },
  wrap: {
    height: 62,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border,
    backgroundColor: theme.colors.bgBase,
  },
  backButton: {
    minWidth: 72,
    paddingVertical: 6,
  },
  backLabel: {
    color: theme.colors.textSecondary,
    fontSize: 20,
    fontFamily: 'DMSans_600SemiBold',
  },
  logoText: {
    color: theme.colors.textPrimary,
    fontSize: 25,
    lineHeight: 30,
    letterSpacing: -0.3,
    fontFamily: 'DMSerifDisplay_400Regular',
  },
  logoButton: {
    paddingVertical: 6,
    paddingHorizontal: 8,
  },
  logoAccent: {
    color: '#7ec8ff',
  },
  searchButton: {
    minWidth: 72,
    paddingVertical: 6,
    alignItems: 'flex-end',
  },
  searchLabel: {
    color: '#7ec8ff',
    fontSize: 22,
    lineHeight: 22,
    fontFamily: 'DMSans_600SemiBold',
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    paddingHorizontal: 12,
    paddingTop: 70,
  },
  dropdownModal: {
    width: '92%',
    maxWidth: 520,
    alignSelf: 'flex-end',
    borderWidth: 1,
    borderColor: theme.colors.borderStrong,
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingTop: 12,
    paddingBottom: 10,
    backgroundColor: theme.colors.bgSurface,
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 8,
  },
  searchInput: {
    flex: 1,
    minWidth: 180,
    borderWidth: 1,
    borderColor: theme.colors.borderStrong,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
    color: theme.colors.textPrimary,
    fontSize: 14,
    fontFamily: 'DMSans_400Regular',
    backgroundColor: theme.colors.bgBase,
  },
  submitButton: {
    height: 38,
    paddingHorizontal: 12,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#7ec8ff',
  },
  submitButtonDisabled: {
    opacity: 0.45,
  },
  submitLabel: {
    color: '#0f1115',
    fontSize: 14,
    fontFamily: 'DMSans_600SemiBold',
  },
  resultsWrap: {
    width: '100%',
    maxHeight: 380,
  },
  section: {
    width: '100%',
    paddingTop: 4,
  },
  sectionLabel: {
    color: theme.colors.textSecondary,
    fontSize: 12,
    lineHeight: 14,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
    fontFamily: 'DMSans_600SemiBold',
    marginBottom: 6,
  },
  resultRow: {
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: 10,
    backgroundColor: theme.colors.bgBase,
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginBottom: 8,
  },
  resultPrimary: {
    color: theme.colors.textPrimary,
    fontSize: 14,
    lineHeight: 18,
    fontFamily: 'DMSans_600SemiBold',
  },
  resultSecondary: {
    marginTop: 2,
    color: theme.colors.textSecondary,
    fontSize: 12,
    lineHeight: 16,
    fontFamily: 'DMSans_400Regular',
  },
  errorText: {
    width: '100%',
    color: theme.colors.danger,
    fontSize: 12,
    lineHeight: 16,
    fontFamily: 'DMSans_400Regular',
  },
  emptyText: {
    width: '100%',
    color: theme.colors.textSecondary,
    fontSize: 12,
    lineHeight: 16,
    fontFamily: 'DMSans_400Regular',
  },
  seeMorePressable: {
    margin: 4,
    width: '100%',
    alignItems: 'center',
    paddingVertical: 6,
  },
  seeMoreLabel: {
    color: '#7ec8ff',
    fontSize: 14,
    lineHeight: 18,
    fontFamily: 'DMSans_600SemiBold',
    textAlign: 'center',
    textDecorationLine: 'underline',
  },
});

export default styles;
