import { StyleSheet } from 'react-native';
import { theme } from '../theme';

const styles = StyleSheet.create({
  outer: {
    zIndex: 20,
    backgroundColor: theme.colors.bgBase,
  },
  wrap: {
    height: 62,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border,
    backgroundColor: theme.colors.bgBase,
  },
  backButton: {
    minWidth: 72,
    paddingVertical: 6,
    justifyContent: 'center',
  },
  logoText: {
    color: theme.colors.textPrimary,
    fontSize: 25,
    lineHeight: 30,
    letterSpacing: -0.3,
    fontFamily: theme.fonts.serif,
  },
  logoButton: {
    paddingVertical: 6,
    paddingHorizontal: 8,
  },
  logoAccent: {
    color: theme.colors.accent,
  },
  searchButton: {
    minWidth: 36,
    paddingVertical: 6,
    alignItems: 'center',
  },
  rightActions: {
    minWidth: 72,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 12,
  },
  notificationButton: {
    paddingVertical: 6,
    paddingHorizontal: 2,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  notificationBadge: {
    position: 'absolute',
    right: -7,
    top: -2,
    minWidth: 17,
    height: 17,
    borderRadius: 8.5,
    paddingHorizontal: 4,
    backgroundColor: theme.colors.notificationBadgeBg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  notificationBadgeText: {
    color: theme.colors.accentOnSolid,
    fontSize: 10,
    lineHeight: 12,
    fontFamily: theme.fonts.bold,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: theme.colors.overlayBackdrop,
    paddingHorizontal: 12,
    paddingTop: 70,
  },
  dropdownModal: {
    width: '92%',
    maxWidth: 520,
    alignSelf: 'flex-end',
    borderWidth: 1,
    borderColor: theme.colors.borderStrong,
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingTop: 12,
    paddingBottom: 10,
    backgroundColor: theme.colors.bgSurface,
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 8,
  },
  searchInput: {
    flex: 1,
    minWidth: 180,
    borderWidth: 1,
    borderColor: theme.colors.borderStrong,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
    color: theme.colors.textPrimary,
    fontSize: 14,
    fontFamily: theme.fonts.regular,
    backgroundColor: theme.colors.bgBase,
  },
  submitButton: {
    height: 38,
    paddingHorizontal: 12,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.colors.accent,
  },
  submitButtonDisabled: {
    opacity: 0.45,
  },
  submitLabel: {
    color: theme.colors.textLight,
    fontSize: 14,
    fontFamily: theme.fonts.semibold,
  },
  resultsWrap: {
    width: '100%',
    maxHeight: 380,
  },
  section: {
    width: '100%',
    paddingTop: 4,
  },
  sectionLabel: {
    color: theme.colors.textSecondary,
    fontSize: 12,
    lineHeight: 14,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
    fontFamily: theme.fonts.semibold,
    marginBottom: 6,
  },
  resultRow: {
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: 10,
    backgroundColor: theme.colors.bgBase,
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginBottom: 8,
  },
  resultPrimary: {
    color: theme.colors.textPrimary,
    fontSize: 14,
    lineHeight: 18,
    fontFamily: theme.fonts.semibold,
  },
  resultSecondary: {
    marginTop: 2,
    color: theme.colors.textSecondary,
    fontSize: 12,
    lineHeight: 16,
    fontFamily: theme.fonts.regular,
  },
  errorText: {
    width: '100%',
    color: theme.colors.danger,
    fontSize: 12,
    lineHeight: 16,
    fontFamily: theme.fonts.regular,
  },
  emptyText: {
    width: '100%',
    color: theme.colors.textSecondary,
    fontSize: 12,
    lineHeight: 16,
    fontFamily: theme.fonts.regular,
  },
  seeMorePressable: {
    margin: 4,
    width: '100%',
    alignItems: 'center',
    paddingVertical: 6,
  },
  seeMoreLabel: {
    color: theme.colors.accent,
    fontSize: 14,
    lineHeight: 18,
    fontFamily: theme.fonts.semibold,
    textAlign: 'center',
    textDecorationLine: 'underline',
  },
  notificationsTable: {
    width: '100%',
    marginTop: 2,
  },
  notificationsHeaderRow: {
    flexDirection: 'row',
    paddingHorizontal: 8,
    paddingBottom: 4,
  },
  notificationsHeaderCellActor: {
    flex: 1.2,
    color: theme.colors.textSecondary,
    fontSize: 11,
    lineHeight: 14,
    fontFamily: theme.fonts.semibold,
    textTransform: 'uppercase',
  },
  notificationsHeaderCellType: {
    flex: 1,
    color: theme.colors.textSecondary,
    fontSize: 11,
    lineHeight: 14,
    fontFamily: theme.fonts.semibold,
    textTransform: 'uppercase',
  },
  notificationsHeaderCellStatus: {
    flex: 0.8,
    color: theme.colors.textSecondary,
    fontSize: 11,
    lineHeight: 14,
    fontFamily: theme.fonts.semibold,
    textTransform: 'uppercase',
    textAlign: 'right',
  },
  notificationsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: 10,
    backgroundColor: theme.colors.bgBase,
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginBottom: 8,
  },
  notificationsActor: {
    flex: 1.2,
    color: theme.colors.textPrimary,
    fontSize: 13,
    lineHeight: 17,
    fontFamily: theme.fonts.regular,
  },
  notificationsType: {
    flex: 1,
    color: theme.colors.textPrimary,
    fontSize: 13,
    lineHeight: 17,
    fontFamily: theme.fonts.semibold,
    textTransform: 'capitalize',
  },
  notificationsStatus: {
    flex: 0.8,
    color: theme.colors.textSecondary,
    fontSize: 12,
    lineHeight: 16,
    fontFamily: theme.fonts.semibold,
    textAlign: 'right',
  },
  notificationsStatusUnread: {
    color: theme.colors.accent,
  },
});

export default styles;
