import { StyleSheet } from 'react-native';
import { theme } from '../theme';
import { commonFollowStyles, commonSearchStyles } from '../styles/commonStyles';

const styles = StyleSheet.create({
  outer: {
    zIndex: 20,
    backgroundColor: theme.colors.bgBase,
  },
  wrap: {
    height: 62,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border,
    backgroundColor: theme.colors.bgBase,
  },
  backButton: {
    width: 64,
    height: 48,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.bgSurface,
    justifyContent: 'center',
    paddingLeft: 16,
  },
  logoText: {
    color: theme.colors.textPrimary,
    fontSize: 25,
    lineHeight: 30,
    letterSpacing: -0.3,
    fontFamily: theme.fonts.serif,
  },
  logoButton: {
    paddingVertical: 6,
    paddingHorizontal: 8,
  },
  logoAccent: {
    color: theme.colors.accent,
  },
  searchButton: {
    minWidth: 36,
    paddingVertical: 6,
    alignItems: 'center',
  },
  rightActions: {
    minWidth: 72,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 12,
  },
  notificationButton: {
    minWidth: 36,
    minHeight: 36,
    paddingVertical: 6,
    paddingHorizontal: 6,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  notificationBadge: {
    position: 'absolute',
    right: -7,
    top: -2,
    minWidth: 17,
    height: 17,
    borderRadius: 8.5,
    paddingHorizontal: 4,
    backgroundColor: theme.colors.accent,
    alignItems: 'center',
    justifyContent: 'center',
  },
  notificationBadgeText: {
    color: theme.colors.textLight,
    fontSize: 10,
    lineHeight: 12,
    fontFamily: theme.fonts.bold,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: theme.colors.overlayBackdrop,
    paddingHorizontal: 12,
    paddingTop: 70,
  },
  dropdownModal: {
    width: '92%',
    maxWidth: 520,
    alignSelf: 'flex-end',
    borderWidth: 1,
    borderColor: theme.colors.borderStrong,
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingTop: 12,
    paddingBottom: 10,
    backgroundColor: theme.colors.bgSurface,
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 8,
  },
  searchInput: {
    flex: 1,
    minWidth: 180,
    borderWidth: 1,
    borderColor: theme.colors.borderStrong,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
    color: theme.colors.textPrimary,
    fontSize: 14,
    fontFamily: theme.fonts.regular,
    backgroundColor: theme.colors.bgBase,
  },
  submitButton: {
    height: 38,
    paddingHorizontal: 12,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.colors.accent,
  },
  submitButtonFullWidth: {
    width: '100%',
  },
  submitButtonDisabled: {
    ...commonSearchStyles.submitButtonDisabled,
  },
  submitLabel: {
    ...commonSearchStyles.submitLabel,
  },
  resultsWrap: {
    width: '100%',
    flexGrow: 0,
  },
  section: {
    width: '100%',
    paddingTop: 4,
  },
  sectionLabel: {
    ...commonSearchStyles.sectionLabel,
  },
  resultRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: 10,
    backgroundColor: theme.colors.bgBase,
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginBottom: 8,
  },
  userInfoPressable: {
    flex: 1,
  },
  resultPrimary: {
    ...commonSearchStyles.resultPrimary,
  },
  resultSecondary: {
    ...commonSearchStyles.resultSecondary,
  },
  followButton: {
    ...commonFollowStyles.buttonBase,
  },
  followButtonActive: {
    ...commonFollowStyles.buttonActive,
  },
  followButtonFollowing: {
    ...commonFollowStyles.buttonFollowing,
  },
  followButtonText: {
    ...commonFollowStyles.textBase,
    lineHeight: 16,
  },
  errorText: {
    width: '100%',
    color: theme.colors.danger,
    fontSize: 12,
    lineHeight: 16,
    fontFamily: theme.fonts.regular,
  },
  emptyText: {
    width: '100%',
    color: theme.colors.textSecondary,
    fontSize: 12,
    lineHeight: 16,
    fontFamily: theme.fonts.regular,
  },
  seeMorePressable: {
    margin: 4,
    width: '100%',
    alignItems: 'center',
    paddingVertical: 6,
  },
  seeMoreLabel: {
    color: theme.colors.accent,
    fontSize: 14,
    lineHeight: 18,
    fontFamily: theme.fonts.semibold,
    textAlign: 'center',
    textDecorationLine: 'underline',
  },
  notificationsScroll: {
    width: '100%',
    marginTop: 2,
    flexGrow: 0,
  },
  notificationsScrollContent: {
    paddingBottom: 2,
  },
  notificationsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: 10,
    backgroundColor: theme.colors.bgBase,
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginBottom: 8,
  },
  notificationsMain: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    paddingRight: 10,
  },
  notificationsUnreadDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: theme.colors.accent,
    marginRight: 8,
  },
  notificationsMessage: {
    flex: 1,
    color: theme.colors.textPrimary,
    fontSize: 13,
    lineHeight: 17,
    fontFamily: theme.fonts.regular,
  },
  notificationsLink: {
    color: theme.colors.accent,
    fontFamily: theme.fonts.semibold,
    textDecorationLine: 'underline',
  },
  notificationsTime: {
    color: theme.colors.textSecondary,
    fontSize: 11,
    lineHeight: 14,
    fontFamily: theme.fonts.regular,
    textAlign: 'right',
    minWidth: 48,
  },
});

export default styles;
