import { StyleSheet } from 'react-native';
import { theme } from '../theme';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    padding: 20,
    backgroundColor: theme.colors.bgSurface,
    position: 'relative',
  },
  panel: {
    width: '100%',
    maxWidth: 560,
    alignSelf: 'center',
    backgroundColor: theme.colors.bgSurface,
    borderWidth: 0.5,
    borderColor: theme.colors.border,
    borderRadius: 16,
    padding: 24,
    gap: 14,
    shadowColor: '#000',
    shadowOpacity: 0.35,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 12 },
    elevation: 6,
  },
  kicker: {
    marginTop: 0,
    marginBottom: 0,
    fontSize: 11,
    letterSpacing: 1,
    textTransform: 'uppercase',
    color: theme.colors.brandText,
    fontFamily: theme.fonts.semibold,
  },
  title: {
    marginTop: 4,
    marginBottom: 8,
    color: theme.colors.textPrimary,
    fontSize: 34,
    lineHeight: 38,
    letterSpacing: -0.4,
    fontFamily: theme.fonts.serif,
  },
  card: {
    backgroundColor: theme.colors.bgRaised,
    borderWidth: 0.5,
    borderColor: theme.colors.border,
    borderRadius: 10,
    paddingVertical: 14,
    paddingHorizontal: 16,
  },
  logoText: {
    color: theme.colors.textPrimary,
    fontSize: 25,
    letterSpacing: -0.3,
    lineHeight: 30,
    fontFamily: theme.fonts.serif,
  },
  logoBrand: { color: theme.colors.brand },
  logoBlue: { color: theme.colors.accent },
  logoutButton: {
    marginTop: 10,
    borderWidth: 0.5,
    borderColor: theme.colors.border,
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 16,
    alignItems: 'center',
    backgroundColor: theme.colors.bgSurface,
  },
  logoutText: {
    color: theme.colors.textSecondary,
    fontSize: 14,
    letterSpacing: 0.2,
    fontFamily: theme.fonts.semibold,
    textTransform: 'uppercase',
  },
});

export default styles;
