import { StyleSheet } from 'react-native';
import { theme } from '../theme';
const HOME_BUTTON_BASE = {
  minHeight: 44,
  borderRadius: 10,
  alignItems: 'center',
  justifyContent: 'center',
  paddingHorizontal: 18,
  paddingVertical: 10,
};
const HOME_BUTTON_LABEL_BASE = {
  color: theme.colors.textLight,
  fontSize: 12,
  lineHeight: 15,
  letterSpacing: 0.8,
  textTransform: 'uppercase',
  fontFamily: theme.fonts.semibold,
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.bgBase,
  },
  content: {
    paddingBottom: 28,
  },
  topLoginBar: {
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border,
    alignItems: 'flex-end',
    backgroundColor: theme.colors.bgBase,
  },
  introHero: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border,
  },
  introHeroText: {
    color: theme.colors.textPrimary,
    fontSize: 34,
    lineHeight: 42,
    letterSpacing: -0.6,
    textAlign: 'center',
    fontFamily: theme.fonts.serif,
    fontStyle: 'italic',
    maxWidth: 420,
  },
  introHeroPoem: {
    color: theme.colors.textPrimary,
    fontSize: 24,
    lineHeight: 36,
    letterSpacing: -0.2,
    textAlign: 'center',
    fontFamily: theme.fonts.serif,
    fontStyle: 'italic',
    maxWidth: 680,
  },
  nav: {
    paddingHorizontal: 18,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: theme.colors.bgSurface,
  },
  brandText: {
    color: theme.colors.textPrimary,
    fontSize: 12,
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    fontFamily: theme.fonts.semibold,
  },
  navButton: {
    backgroundColor: theme.colors.textPrimary,
    borderRadius: 4,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  navButtonText: {
    color: theme.colors.bgBase,
    fontSize: 12,
    letterSpacing: 0.4,
    textTransform: 'uppercase',
    fontFamily: theme.fonts.semibold,
  },
  hero: {
    paddingHorizontal: 30,
    paddingVertical: 80,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border,
  },
  dualProductSection: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 36,
    minHeight: 220,
  },
  dualProductColumn: {
    flex: 1,
    alignItems: 'center',
    paddingHorizontal: 14,
    gap: 14,
  },
  dualProductDividerWrap: {
    width: 1,
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  dualProductDivider: {
    width: 1,
    height: '50%',
    backgroundColor: theme.colors.textSecondary,
  },
  dualProductLogo: {
    fontSize: 34,
    lineHeight: 40,
    letterSpacing: -0.6,
  },
  dualProductDescription: {
    color: theme.colors.textSecondary,
    fontSize: 14,
    lineHeight: 22,
    textAlign: 'center',
    fontFamily: theme.fonts.regular,
    minHeight: 44,
  },
  dualProductButton: {
    ...HOME_BUTTON_BASE,
    minWidth: 168,
  },
  eyebrowRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    marginBottom: 26,
  },
  eyebrowLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flexShrink: 1,
  },
  eyebrowLine: {
    width: 54,
    height: 1,
    backgroundColor: theme.colors.textSecondary,
  },
  eyebrow: {
    color: theme.colors.textSecondary,
    fontSize: 11,
    letterSpacing: 3,
    textTransform: 'uppercase',
    fontFamily: theme.fonts.semibold,
  },
  eyebrowLoginButton: {
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginLeft: 12,
    backgroundColor: 'transparent',
  },
  eyebrowLoginText: {
    color: theme.colors.textPrimary,
    fontSize: 11,
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    fontFamily: theme.fonts.semibold,
  },
  heroTitleWrap: {
    marginBottom: 20,
  },
  heroTitleRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 8,
  },
  heroTitleScript: {
    color: theme.colors.textPrimary,
    fontSize: 70,
    lineHeight: 74,
    letterSpacing: -0.6,
    fontFamily: theme.fonts.serif,
    fontStyle: 'italic',
  },
  heroTitleBold: {
    color: theme.colors.textPrimary,
    fontSize: 82,
    lineHeight: 82,
    letterSpacing: -1.6,
    textTransform: 'lowercase',
    fontFamily: theme.fonts.semibold,
  },
  heroSubcopy: {
    color: theme.colors.textSecondary,
    fontSize: 16,
    lineHeight: 28,
    fontFamily: theme.fonts.regular,
    maxWidth: 700,
  },
  heroActions: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 24,
  },
  heroActionsSmallScreen: {
    width: '100%',
  },
  heroButton: {
    ...HOME_BUTTON_BASE,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  heroButtonSmallScreen: {
    flex: 1,
    minWidth: 0,
    paddingHorizontal: 20,
  },
  openButton: {
    flex: 0.33,
    backgroundColor: theme.colors.accent,
  },
  secondButton: {
    flex: 0.33,
    backgroundColor: theme.colors.brand,
  },
  previewWrap: {
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border,
  },
  previewPanelTop: {
    flex: 1,
    width: '100%',
    backgroundColor: theme.colors.accentBg,
    padding: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  previewPanelBottom: {
    flex: 1,
    width: '100%',
    backgroundColor: theme.colors.accentBg,
    padding: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  previewBadgeOpen: {
    alignSelf: 'flex-start',
    backgroundColor: theme.colors.accent,
    color: theme.colors.textLight,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    fontSize: 10,
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    marginBottom: 12,
    fontFamily: theme.fonts.semibold,
  },
  previewTooltipCard: {
    width: '100%',
    backgroundColor: theme.colors.bgSurface,
    borderWidth: 1,
    borderColor: theme.colors.accent,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginBottom: 12,
  },
  previewTooltipCardSecond: {
    borderColor: theme.colors.brand,
  },
  previewTooltipTitle: {
    color: theme.colors.accent,
    fontSize: 12,
    lineHeight: 17,
    marginBottom: 4,
    fontFamily: theme.fonts.semibold,
  },
  previewTooltipTitleSecond: {
    color: theme.colors.brand,
  },
  previewTooltipText: {
    color: theme.colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
    fontFamily: theme.fonts.regular,
  },
  previewBadgeSecond: {
    alignSelf: 'flex-start',
    backgroundColor: theme.colors.brand,
    color: theme.colors.textLight,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    fontSize: 10,
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    marginBottom: 12,
    fontFamily: theme.fonts.semibold,
  },
  previewCardOpen: {
    width: '100%',
    backgroundColor: theme.colors.bgSurface,
    borderColor: theme.colors.accent,
    borderWidth: 1,
    borderRadius: 8,
    padding: 12,
    gap: 8,
  },
  previewCardOpenWrap: {
    width: '100%',
    position: 'relative',
  },
  previewHotspot: {
    position: 'absolute',
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: theme.colors.accent,
    backgroundColor: theme.colors.bgSurface,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: theme.colors.accent,
    shadowOpacity: 0.24,
    shadowRadius: 7,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  previewHotspotActive: {
    backgroundColor: theme.colors.accent,
    transform: [{ scale: 1.06 }],
  },
  previewHotspotText: {
    color: theme.colors.accent,
    fontSize: 11,
    lineHeight: 13,
    fontFamily: theme.fonts.semibold,
  },
  previewHotspotTextActive: {
    color: theme.colors.textLight,
  },
  previewHotspotMarkdown: {
    top: 40,
    right: 12,
  },
  previewHotspotReactions: {
    bottom: 42,
    left: 14,
  },
  previewHotspotSave: {
    bottom: 10,
    right: 22,
  },
  previewCardSecond: {
    width: '100%',
    backgroundColor: 'transparent',
    borderColor: theme.colors.brand,
    borderWidth: 1,
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
    height: 560,
    overflow: 'hidden',
  },
  previewSecondImage: {
    height: 500,
    maxHeight: '100%',
    aspectRatio: 731 / 1695,
    borderRadius: 6,
    backgroundColor: 'transparent',
  },
  previewCardSecondWrap: {
    width: '100%',
    position: 'relative',
  },
  previewHotspotSecond: {
    position: 'absolute',
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: theme.colors.brand,
    backgroundColor: theme.colors.bgSurface,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: theme.colors.brand,
    shadowOpacity: 0.24,
    shadowRadius: 7,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  previewHotspotSecondActive: {
    backgroundColor: theme.colors.brand,
    transform: [{ scale: 1.06 }],
  },
  previewHotspotSecondText: {
    color: theme.colors.brand,
    fontSize: 11,
    lineHeight: 13,
    fontFamily: theme.fonts.semibold,
  },
  previewHotspotSecondTextActive: {
    color: theme.colors.textLight,
  },
  previewHotspotSecondCapture: {
    top: 98,
    left: '39%',
  },
  previewHotspotSecondMarkdown: {
    top: 190,
    right: '39%',
  },
  previewHotspotSecondSearchable: {
    bottom: 98,
    left: '40%',
  },
  previewMetaOpen: {
    color: theme.colors.accent,
    fontSize: 11,
    fontFamily: theme.fonts.semibold,
  },
  previewMetaSecond: {
    color: theme.colors.brand,
    fontSize: 11,
    fontFamily: theme.fonts.semibold,
  },
  previewText: {
    color: theme.colors.textPrimary,
    fontSize: 13,
    lineHeight: 19,
    fontFamily: theme.fonts.regular,
  },
  previewTags: {
    color: theme.colors.textSecondary,
    fontSize: 11,
    fontFamily: theme.fonts.regular,
  },
  marqueeBar: {
    backgroundColor: theme.colors.bgSurface,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border,
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  marqueeText: {
    color: theme.colors.textMuted,
    fontSize: 11,
    letterSpacing: 0.6,
    textTransform: 'uppercase',
    fontFamily: theme.fonts.regular,
  },
  productsSection: {
    paddingHorizontal: 0,
    paddingVertical: 0,
    gap: 0,
  },
  productCard: {
    backgroundColor: theme.colors.bgBase,
    paddingHorizontal: 24,
    paddingTop: 34,
    paddingBottom: 48,
  },
  productNumber: {
    color: theme.colors.textPrimary,
    fontSize: 13,
    letterSpacing: 0.8,
    marginBottom: 34,
    fontFamily: theme.fonts.regular,
  },
  productTitleWrap: {
    marginBottom: 0,
    width: '100%',
  },
  productTitleScript: {
    fontSize: 66,
    lineHeight: 72,
    letterSpacing: -0.8,
    fontFamily: theme.fonts.serif,
    fontStyle: 'italic',
  },
  productLogoText: {
    fontSize: 66,
    lineHeight: 72,
    letterSpacing: -0.8,
    fontFamily: theme.fonts.serif,
  },
  productLogoTextCompact: {
    fontSize: 56,
    lineHeight: 62,
  },
  productSecondLogoTextCompact: {
    fontSize: 48,
    lineHeight: 54,
  },
  productLogoNoWrap: {
    width: '100%',
    includeFontPadding: false,
  },
  productLogoAccent: {
    color: theme.colors.accent,
  },
  productTagline: {
    color: theme.colors.textSecondary,
    fontSize: 16,
    lineHeight: 22,
    letterSpacing: 3.3,
    textTransform: 'uppercase',
    marginBottom: 28,
    fontFamily: theme.fonts.semibold,
  },
  productDescription: {
    color: theme.colors.textSecondary,
    fontSize: 16,
    lineHeight: 26,
    marginBottom: 34,
    fontFamily: theme.fonts.regular,
  },
  featureList: {
    gap: 22,
    marginBottom: 42,
  },
  featureRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 18,
  },
  featureDot: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 6,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  featureDotInner: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  featureText: {
    color: theme.colors.textSecondary,
    flex: 1,
    fontSize: 16,
    lineHeight: 26,
    fontFamily: theme.fonts.regular,
  },
  productButton: {
    ...HOME_BUTTON_BASE,
    alignSelf: 'flex-start',
    minWidth: 220,
  },
  dividerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 16,
    paddingVertical: 18,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: theme.colors.border,
  },
  dividerText: {
    color: theme.colors.textSecondary,
    fontSize: 10,
    letterSpacing: 1,
    textTransform: 'uppercase',
    fontFamily: theme.fonts.semibold,
  },
  workflowSection: {
    backgroundColor: theme.colors.accentBg,
    paddingHorizontal: 40,
    paddingVertical: 40,
  },
  workflowLabel: {
    color: theme.colors.textSecondary,
    fontSize: 11,
    letterSpacing: 1,
    textTransform: 'uppercase',
    marginBottom: 8,
    fontFamily: theme.fonts.semibold,
  },
  workflowTitle: {
    color: theme.colors.textPrimary,
    fontSize: 30,
    lineHeight: 34,
    letterSpacing: -0.5,
    marginBottom: 16,
    fontFamily: theme.fonts.serif,
  },
  stepGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    columnGap: 10,
    rowGap: 10,
  },
  stepCard: {
    backgroundColor: theme.colors.bgRaised,
    borderColor: theme.colors.border,
    borderWidth: 1,
    borderRadius: 10,
    padding: 14,
    width: '47.5%',
  },
  stepNum: {
    color: theme.colors.textMuted,
    fontSize: 10,
    letterSpacing: 0.8,
    marginBottom: 8,
    fontFamily: theme.fonts.regular,
  },
  stepIcon: {
    fontSize: 20,
    marginBottom: 8,
  },
  stepTitle: {
    color: theme.colors.textPrimary,
    fontSize: 15,
    lineHeight: 20,
    marginBottom: 6,
    fontFamily: theme.fonts.semibold,
  },
  stepDesc: {
    color: theme.colors.textSecondary,
    fontSize: 13,
    lineHeight: 19,
    fontFamily: theme.fonts.regular,
  },
  testimonialSection: {
    padding: 16,
    gap: 6,
    borderTopWidth: 1,
    borderTopColor: theme.colors.border,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border,
    backgroundColor: theme.colors.bgSurface,
  },
  quote: {
    color: theme.colors.textPrimary,
    fontSize: 18,
    lineHeight: 28,
    fontFamily: theme.fonts.serif,
  },
  quoteAuthor: {
    color: theme.colors.textSecondary,
    fontSize: 12,
    marginBottom: 10,
    fontFamily: theme.fonts.regular,
  },
  ctaSection: {
    paddingHorizontal: 0,
    paddingVertical: 0,
    gap: 0,
  },
  ctaSectionBlock: {
    borderTopWidth: 1,
    borderTopColor: theme.colors.border,
  },
  ctaSectionDivider: {
    height: 28,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.bgSurface,
  },
  ctaBlock: {
    borderRadius: 0,
    paddingHorizontal: 28,
    paddingTop: 46,
    paddingBottom: 56,
    gap: 22,
    minHeight: 420,
    justifyContent: 'center',
  },
  openCta: {
    backgroundColor: theme.colors.bgBase,
  },
  secondCta: {
    backgroundColor: theme.colors.accentBg,
  },
  ctaTitle: {
    color: theme.colors.textPrimary,
    fontSize: 62,
    lineHeight: 68,
    letterSpacing: -1,
    fontFamily: theme.fonts.serif,
    fontStyle: 'italic',
    maxWidth: 360,
  },
  ctaBody: {
    color: theme.colors.textSecondary,
    fontSize: 18,
    lineHeight: 33,
    fontFamily: theme.fonts.regular,
    maxWidth: 360,
  },
  ctaButtonLight: {
    ...HOME_BUTTON_BASE,
    alignSelf: 'flex-start',
    minWidth: 220,
  },
  footer: {
    borderTopWidth: 1,
    borderTopColor: theme.colors.border,
    paddingHorizontal: 24,
    paddingVertical: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  footerText: {
    color: theme.colors.textSecondary,
    fontSize: 12,
    letterSpacing: 0.6,
    fontFamily: theme.fonts.regular,
  },
  buttonLabelText: {
    ...HOME_BUTTON_LABEL_BASE,
  },
  openAccentText: {
    color: theme.colors.accent,
    fontSize: 28,
    letterSpacing: 0.3,
    fontFamily: theme.fonts.semibold,
  },
  secondAccentText: {
    color: theme.colors.brand,
    fontSize: 28,
    letterSpacing: 0.3,
    fontFamily: theme.fonts.semibold,
  },
  openAccentBg: {
    backgroundColor: theme.colors.accent,
  },
  openAccentBorder: {
    borderColor: theme.colors.accent,
  },
  secondAccentBg: {
    backgroundColor: theme.colors.brand,
  },
  secondAccentBorder: {
    borderColor: theme.colors.brand,
  },
  openBrainLogoText: {
    color: theme.colors.textPrimary,
    fontSize: 21,
    lineHeight: 26,
    letterSpacing: -0.3,
    fontFamily: theme.fonts.serif,
  },
  openBrainLogoAccent: {
    color: theme.colors.accent,
  },
  heroLogoInline: {
    fontSize: 18,
    lineHeight: 28,
    letterSpacing: -0.2,
    backgroundColor: theme.colors.bgBase,
  },
  buttonLogoText: {
    fontSize: 12,
    lineHeight: 15,
    letterSpacing: 0.1,
    color: theme.colors.textLight,
  },
  buttonLogoAccent: {
    color: theme.colors.textLight,
  },
  badgeLogoText: {
    fontSize: 10,
    lineHeight: 14,
    letterSpacing: 0.1,
    color: theme.colors.textPrimary,
  },
  badgeLogoAccent: {
    color: theme.colors.textPrimary,
  },
  badgeSecondLogoAccent: {
    color: theme.colors.textPrimary,
  },
  ctaLogoInline: {
    fontSize: 16,
    lineHeight: 26,
    letterSpacing: -0.2,
  },
  footerLogoInline: {
    fontSize: 16,
    lineHeight: 24,
    letterSpacing: -0.2,
  },
  stepLogoInline: {
    fontSize: 13,
    lineHeight: 19,
    letterSpacing: -0.1,
  },
  stepLogoAccent: {
    color: theme.colors.brand,
  },
  secondBrainLogoText: {
    color: theme.colors.textPrimary,
    fontSize: 21,
    lineHeight: 26,
    letterSpacing: -0.3,
    fontFamily: theme.fonts.serif,
  },
  secondBrainLogoAccent: {
    color: theme.colors.brand,
  },
  productSecondLogoAccent: {
    color: theme.colors.brand,
  },
});

export default styles;
