import { StyleSheet } from 'react-native';
import { theme } from '../theme';
import { openBrainStyle } from '../constants/openbrainStyle';
const HOME_BUTTON_BASE = {
  minHeight: 44,
  borderRadius: 10,
  alignItems: 'center',
  justifyContent: 'center',
  paddingHorizontal: 18,
  paddingVertical: 10,
};
const HOME_BUTTON_LABEL_BASE = {
  color: openBrainStyle.textLight,
  fontSize: 12,
  lineHeight: 15,
  letterSpacing: 0.8,
  textTransform: 'uppercase',
  fontFamily: openBrainStyle.fontSemiBold,
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.bgBase,
  },
  content: {
    paddingBottom: 28,
  },
  nav: {
    paddingHorizontal: 18,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: theme.colors.bgSurface,
  },
  brandText: {
    color: theme.colors.textPrimary,
    fontSize: 12,
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    fontFamily: openBrainStyle.fontSemiBold,
  },
  navButton: {
    backgroundColor: theme.colors.textPrimary,
    borderRadius: 4,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  navButtonText: {
    color: theme.colors.bgBase,
    fontSize: 12,
    letterSpacing: 0.4,
    textTransform: 'uppercase',
    fontFamily: openBrainStyle.fontSemiBold,
  },
  hero: {
    paddingHorizontal: 30,
    paddingVertical: 80,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border,
  },
  eyebrowRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 26,
  },
  eyebrowLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flexShrink: 1,
  },
  eyebrowLine: {
    width: 54,
    height: 1,
    backgroundColor: theme.colors.textSecondary,
  },
  eyebrow: {
    color: theme.colors.textSecondary,
    fontSize: 11,
    letterSpacing: 3,
    textTransform: 'uppercase',
    fontFamily: openBrainStyle.fontSemiBold,
  },
  eyebrowLoginButton: {
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginLeft: 12,
    backgroundColor: 'transparent',
  },
  eyebrowLoginText: {
    color: theme.colors.textPrimary,
    fontSize: 11,
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    fontFamily: openBrainStyle.fontSemiBold,
  },
  heroTitleWrap: {
    marginBottom: 20,
  },
  heroTitleRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 8,
  },
  heroTitleScript: {
    color: theme.colors.textPrimary,
    fontSize: 70,
    lineHeight: 74,
    letterSpacing: -0.6,
    fontFamily: openBrainStyle.fontSerif,
    fontStyle: 'italic',
  },
  heroTitleBold: {
    color: theme.colors.textPrimary,
    fontSize: 82,
    lineHeight: 82,
    letterSpacing: -1.6,
    textTransform: 'lowercase',
    fontFamily: openBrainStyle.fontSemiBold,
  },
  heroSubcopy: {
    color: theme.colors.textSecondary,
    fontSize: 16,
    lineHeight: 28,
    fontFamily: openBrainStyle.fontRegular,
    maxWidth: 700,
  },
  heroActions: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 24,
  },
  heroButton: {
    ...HOME_BUTTON_BASE,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  openButton: {
    flex: 0.33,
    backgroundColor: openBrainStyle.accent,
  },
  secondButton: {
    flex: 0.33,
    backgroundColor: openBrainStyle.second,
  },
  previewWrap: {
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border,
  },
  previewPanelTop: {
    backgroundColor: openBrainStyle.accentBg,
    padding: 30,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border,
  },
  previewPanelBottom: {
    backgroundColor: openBrainStyle.accentBg,
    padding: 30,
  },
  previewBadgeOpen: {
    alignSelf: 'flex-start',
    backgroundColor: openBrainStyle.accent,
    color: theme.colors.textPrimary,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    fontSize: 10,
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    marginBottom: 12,
    fontFamily: openBrainStyle.fontSemiBold,
  },
  previewBadgeSecond: {
    alignSelf: 'flex-start',
    backgroundColor: openBrainStyle.second,
    color: theme.colors.textPrimary,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    fontSize: 10,
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    marginBottom: 12,
    fontFamily: openBrainStyle.fontSemiBold,
  },
  previewCardOpen: {
    backgroundColor: theme.colors.bgSurface,
    borderColor: openBrainStyle.accent,
    borderWidth: 1,
    borderRadius: 8,
    padding: 12,
    gap: 8,
  },
  previewCardSecond: {
    backgroundColor: theme.colors.bgSurface,
    borderColor: openBrainStyle.second,
    borderWidth: 1,
    borderRadius: 8,
    padding: 12,
    gap: 8,
  },
  previewMetaOpen: {
    color: openBrainStyle.accent,
    fontSize: 11,
    fontFamily: openBrainStyle.fontSemiBold,
  },
  previewMetaSecond: {
    color: openBrainStyle.second,
    fontSize: 11,
    fontFamily: openBrainStyle.fontSemiBold,
  },
  previewText: {
    color: theme.colors.textPrimary,
    fontSize: 13,
    lineHeight: 19,
    fontFamily: openBrainStyle.fontRegular,
  },
  previewTags: {
    color: theme.colors.textSecondary,
    fontSize: 11,
    fontFamily: openBrainStyle.fontRegular,
  },
  marqueeBar: {
    backgroundColor: theme.colors.bgSurface,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border,
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  marqueeText: {
    color: theme.colors.textMuted,
    fontSize: 11,
    letterSpacing: 0.6,
    textTransform: 'uppercase',
    fontFamily: openBrainStyle.fontRegular,
  },
  productsSection: {
    paddingHorizontal: 0,
    paddingVertical: 0,
    gap: 0,
  },
  productCard: {
    paddingHorizontal: 24,
    paddingTop: 34,
    paddingBottom: 48,
  },
  productNumber: {
    color: theme.colors.textPrimary,
    fontSize: 13,
    letterSpacing: 0.8,
    marginBottom: 34,
    fontFamily: openBrainStyle.fontRegular,
  },
  productTitleWrap: {
    marginBottom: 0,
  },
  productTitleScript: {
    fontSize: 66,
    lineHeight: 72,
    letterSpacing: -0.8,
    fontFamily: openBrainStyle.fontSerif,
    fontStyle: 'italic',
  },
  productLogoText: {
    fontSize: 66,
    lineHeight: 72,
    letterSpacing: -0.8,
    fontFamily: openBrainStyle.fontSerif,
  },
  productLogoAccent: {
    color: openBrainStyle.accent,
  },
  productTagline: {
    color: theme.colors.textPrimary,
    fontSize: 16,
    lineHeight: 22,
    letterSpacing: 3.3,
    textTransform: 'uppercase',
    marginBottom: 28,
    fontFamily: openBrainStyle.fontSemiBold,
  },
  productDescription: {
    color: theme.colors.textPrimary,
    fontSize: 16,
    lineHeight: 26,
    marginBottom: 34,
    fontFamily: openBrainStyle.fontRegular,
  },
  featureList: {
    gap: 22,
    marginBottom: 42,
  },
  featureRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 18,
  },
  featureDot: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 6,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  featureDotInner: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  featureText: {
    color: theme.colors.textPrimary,
    flex: 1,
    fontSize: 16,
    lineHeight: 26,
    fontFamily: openBrainStyle.fontRegular,
  },
  productButton: {
    ...HOME_BUTTON_BASE,
    alignSelf: 'flex-start',
    minWidth: 220,
  },
  dividerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 16,
    paddingVertical: 18,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: theme.colors.border,
  },
  dividerText: {
    color: theme.colors.textSecondary,
    fontSize: 10,
    letterSpacing: 1,
    textTransform: 'uppercase',
    fontFamily: openBrainStyle.fontSemiBold,
  },
  workflowSection: {
    backgroundColor: openBrainStyle.accentBg,
    paddingHorizontal: 40,
    paddingVertical: 40,
  },
  workflowLabel: {
    color: theme.colors.textSecondary,
    fontSize: 11,
    letterSpacing: 1,
    textTransform: 'uppercase',
    marginBottom: 8,
    fontFamily: openBrainStyle.fontSemiBold,
  },
  workflowTitle: {
    color: theme.colors.textPrimary,
    fontSize: 30,
    lineHeight: 34,
    letterSpacing: -0.5,
    marginBottom: 16,
    fontFamily: openBrainStyle.fontSerif,
  },
  stepGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    columnGap: 10,
    rowGap: 10,
  },
  stepCard: {
    backgroundColor: theme.colors.bgRaised,
    borderColor: theme.colors.border,
    borderWidth: 1,
    borderRadius: 10,
    padding: 14,
    width: '48.5%',
  },
  stepNum: {
    color: theme.colors.textMuted,
    fontSize: 10,
    letterSpacing: 0.8,
    marginBottom: 8,
    fontFamily: openBrainStyle.fontRegular,
  },
  stepIcon: {
    fontSize: 20,
    marginBottom: 8,
  },
  stepTitle: {
    color: theme.colors.textPrimary,
    fontSize: 15,
    lineHeight: 20,
    marginBottom: 6,
    fontFamily: openBrainStyle.fontSemiBold,
  },
  stepDesc: {
    color: theme.colors.textSecondary,
    fontSize: 13,
    lineHeight: 19,
    fontFamily: openBrainStyle.fontRegular,
  },
  testimonialSection: {
    padding: 16,
    gap: 6,
    borderTopWidth: 1,
    borderTopColor: theme.colors.border,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border,
    backgroundColor: theme.colors.bgSurface,
  },
  quote: {
    color: theme.colors.textPrimary,
    fontSize: 18,
    lineHeight: 28,
    fontFamily: openBrainStyle.fontSerif,
  },
  quoteAuthor: {
    color: theme.colors.textSecondary,
    fontSize: 12,
    marginBottom: 10,
    fontFamily: openBrainStyle.fontRegular,
  },
  ctaSection: {
    paddingHorizontal: 0,
    paddingVertical: 0,
    gap: 0,
  },
  ctaBlock: {
    borderRadius: 0,
    paddingHorizontal: 28,
    paddingTop: 46,
    paddingBottom: 56,
    gap: 22,
    minHeight: 420,
    justifyContent: 'center',
  },
  openCta: {
  },
  secondCta: {
    backgroundColor: openBrainStyle.accentBg,
  },
  ctaTitle: {
    color: openBrainStyle.pureWhite,
    fontSize: 62,
    lineHeight: 68,
    letterSpacing: -1,
    fontFamily: openBrainStyle.fontSerif,
    fontStyle: 'italic',
    maxWidth: 360,
  },
  ctaBody: {
    color: openBrainStyle.white90,
    fontSize: 18,
    lineHeight: 33,
    fontFamily: openBrainStyle.fontRegular,
    maxWidth: 360,
  },
  ctaButtonLight: {
    ...HOME_BUTTON_BASE,
    alignSelf: 'flex-start',
    minWidth: 220,
  },
  footer: {
    borderTopWidth: 1,
    borderTopColor: theme.colors.border,
    paddingHorizontal: 24,
    paddingVertical: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  footerText: {
    color: theme.colors.textSecondary,
    fontSize: 12,
    letterSpacing: 0.6,
    fontFamily: openBrainStyle.fontRegular,
  },
  buttonLabelText: {
    ...HOME_BUTTON_LABEL_BASE,
  },
  openAccentText: {
    color: openBrainStyle.accent,
    fontSize: 28,
    letterSpacing: 0.3,
    fontFamily: openBrainStyle.fontSemiBold,
  },
  secondAccentText: {
    color: openBrainStyle.second,
    fontSize: 28,
    letterSpacing: 0.3,
    fontFamily: openBrainStyle.fontSemiBold,
  },
  openAccentBg: {
    backgroundColor: openBrainStyle.accent,
  },
  openAccentBorder: {
    borderColor: openBrainStyle.accent,
  },
  secondAccentBg: {
    backgroundColor: openBrainStyle.second,
  },
  secondAccentBorder: {
    borderColor: openBrainStyle.second,
  },
  openBrainLogoText: {
    color: theme.colors.textPrimary,
    fontSize: 25,
    lineHeight: 30,
    letterSpacing: -0.3,
    fontFamily: openBrainStyle.fontSerif,
  },
  openBrainLogoAccent: {
    color: openBrainStyle.accent,
  },
  heroLogoInline: {
    fontSize: 18,
    lineHeight: 28,
    letterSpacing: -0.2,
  },
  buttonLogoText: {
    fontSize: 12,
    lineHeight: 15,
    letterSpacing: 0.1,
    color: openBrainStyle.textLight,
  },
  buttonLogoAccent: {
    color: openBrainStyle.textLight,
  },
  badgeLogoText: {
    fontSize: 10,
    lineHeight: 14,
    letterSpacing: 0.1,
    color: theme.colors.textPrimary,
  },
  badgeLogoAccent: {
    color: theme.colors.textPrimary,
  },
  badgeSecondLogoAccent: {
    color: theme.colors.textPrimary,
  },
  ctaLogoInline: {
    fontSize: 16,
    lineHeight: 26,
    letterSpacing: -0.2,
  },
  footerLogoInline: {
    fontSize: 16,
    lineHeight: 24,
    letterSpacing: -0.2,
  },
  stepLogoInline: {
    fontSize: 13,
    lineHeight: 19,
    letterSpacing: -0.1,
  },
  stepLogoAccent: {
    color: theme.colors.brand,
  },
  secondBrainLogoText: {
    color: theme.colors.textPrimary,
    fontSize: 25,
    lineHeight: 30,
    letterSpacing: -0.3,
    fontFamily: openBrainStyle.fontSerif,
  },
  secondBrainLogoAccent: {
    color: theme.colors.brand,
  },
  productSecondLogoAccent: {
    color: theme.colors.brand,
  },
});

export default styles;
