import { StyleSheet } from 'react-native';
import { theme } from '../theme';

export const SWIPE_ACTION_WIDTH = 88;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.bgBase,
    paddingHorizontal: 12,
    paddingTop: 12,
    paddingBottom: 0,
  },
  row: { flexDirection: 'row', gap: 8, marginBottom: 8 },
  statsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginBottom: 10 },
  statsGridSmall: { flexWrap: 'nowrap', gap: 4 },
  filterSection: { gap: 8, marginBottom: 10 },
  filterHeaderRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
  filterDropdownContent: {
    backgroundColor: theme.colors.bgRaised,
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: 10,
    padding: 10,
    gap: 8,
  },
  filterDropdownToggle: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.bgRaised,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  filterDropdownChevron: { color: theme.colors.textMuted, fontSize: 10, fontWeight: '700' },
  filterDropdownChevronIcon: { color: theme.colors.textMuted },
  filterLabel: { fontSize: 11, color: theme.colors.textMuted, letterSpacing: 0.66, textTransform: 'uppercase', fontWeight: '500' },
  archivedToggle: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  archivedToggleDropdown: {
    width: '100%',
    justifyContent: 'space-between',
    backgroundColor: theme.colors.bgBase,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  archivedToggleText: { color: theme.colors.textSecondary, fontSize: 11 },
  filterRow: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: 8 },
  filterRowLabel: { fontSize: 11, color: theme.colors.textMuted, letterSpacing: 0.66, textTransform: 'uppercase', fontWeight: '500' },
  filterSearchInput: {
    borderWidth: 1,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.bgRaised,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: theme.colors.textPrimary,
    fontSize: 13,
  },
  pill: {
    borderWidth: 1,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.bgRaised,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  pillActive: { borderColor: theme.colors.brand, backgroundColor: theme.colors.brandDim },
  pillDisabled: { opacity: 0.55 },
  pillText: { fontSize: 11, color: theme.colors.textSecondary },
  pillTextActive: { color: theme.colors.brandText },
  pillTextDisabled: { color: theme.colors.textMuted },
  statCard: {
    width: '23.7%',
    minWidth: 70,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.bgSurface,
    paddingVertical: 8,
    paddingHorizontal: 6,
    overflow: 'hidden',
  },
  statCardSmall: {
    width: '24%',
    minWidth: 0,
    paddingHorizontal: 5,
  },
  statCardActive: { borderColor: theme.colors.brand, backgroundColor: theme.colors.brandDim },
  statGlow: {
    position: 'absolute',
    top: -10,
    left: -10,
    width: 40,
    height: 40,
    borderRadius: 999,
  },
  statCount: { fontSize: 20, lineHeight: 22, fontWeight: '500' },
  statLabel: {
    fontSize: 9,
    lineHeight: 12,
    color: theme.colors.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    fontWeight: '500',
  },
  statLabelSmall: {
    fontSize: 8,
    lineHeight: 10,
    letterSpacing: 0.2,
  },
  statLabelActive: { color: theme.colors.brandText },
  list: { flex: 1 },
  listContent: { paddingBottom: 84 },
  sectionHeaderText: {
    fontSize: 11,
    fontWeight: '500',
    color: theme.colors.textMuted,
    letterSpacing: 0.66,
    textTransform: 'uppercase',
    marginBottom: 6,
    marginTop: 6
  },
  typebarRow: {
    position: 'absolute',
    left: 12,
    right: 12,
    bottom: 10,
    zIndex: 10,
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 10,
  },
  typebarInput: {
    flex: 1,
    backgroundColor: theme.colors.bgRaised,
    color: theme.colors.textPrimary,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: theme.colors.border,
    minHeight: 38,
    paddingHorizontal: 16,
    paddingVertical: 8,
    fontSize: 13,
    lineHeight: 19,
  },
  typebarInputSmall: {
    paddingHorizontal: 12,
    fontSize: 11,
    lineHeight: 14,
  },
  typebarButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.brand,
    alignItems: 'center',
    justifyContent: 'center',
  },
  typebarUploadButton: {
    backgroundColor: theme.colors.bgRaised,
  },
  typebarActionWrap: {
    position: 'relative',
    alignItems: 'center',
  },
  typebarTooltip: {
    position: 'absolute',
    bottom: 42,
    backgroundColor: '#111827',
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderWidth: 1,
    borderColor: theme.colors.border,
    zIndex: 20,
  },
  typebarTooltipText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: '600',
  },
  typebarButtonDisabled: {
    backgroundColor: theme.colors.bgRaised,
  },
  typebarButtonText: { color: '#fff', fontWeight: '700', fontSize: 16, lineHeight: 16 },
  typebarButtonIcon: { color: '#fff' },
  typebarButtonTextDisabled: { color: theme.colors.textMuted },
  typebarButtonIconDisabled: { color: theme.colors.textMuted },
  typebarUploadButtonText: { color: theme.colors.textSecondary, fontSize: 15 },
  typebarUploadButtonIcon: { color: theme.colors.textSecondary },
  settingsPanel: {
    width: '100%',
    maxWidth: 620,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.bgBase,
    padding: 16,
    gap: 12,
  },
  settingsScroll: { maxHeight: 560 },
  settingsScrollContent: { gap: 12 },
  settingsTitle: { color: theme.colors.textPrimary, fontSize: 18, fontWeight: '700' },
  settingsLabel: { color: theme.colors.textSecondary, fontSize: 11 },
  settingsInput: {
    borderWidth: 1,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.bgRaised,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: theme.colors.textPrimary,
    fontSize: 13,
  },
  settingsDropdown: {
    backgroundColor: theme.colors.bgRaised,
    borderColor: theme.colors.border,
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 12,
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
  },
  settingsDropdownWrapper: {
    position: 'relative',
    zIndex: 40,
  },
  settingsDropdownText: {
    color: theme.colors.textPrimary,
    fontFamily: theme.fonts.regular,
    fontSize: 14,
  },
  settingsDropdownChevron: {
    color: theme.colors.textSecondary,
    fontFamily: theme.fonts.semibold,
    fontSize: 12,
  },
  settingsDropdownChevronIcon: { color: theme.colors.textSecondary },
  settingsDropdownList: {
    position: 'absolute',
    top: 48,
    left: 0,
    right: 0,
    backgroundColor: theme.colors.bgRaised,
    borderColor: theme.colors.border,
    borderWidth: 1,
    borderRadius: 10,
    maxHeight: 220,
    zIndex: 30,
    elevation: 8,
  },
  settingsDropdownListContent: { paddingVertical: 4 },
  settingsDropdownSearchInput: {
    backgroundColor: theme.colors.bgSurface,
    borderColor: theme.colors.border,
    borderWidth: 1,
    borderRadius: 8,
    color: theme.colors.textPrimary,
    fontFamily: theme.fonts.regular,
    fontSize: 13,
    marginHorizontal: 8,
    marginBottom: 4,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  settingsDropdownOption: {
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  settingsDropdownOptionSelected: {
    backgroundColor: theme.colors.accentDim,
  },
  settingsDropdownOptionText: {
    color: theme.colors.textSecondary,
    fontFamily: theme.fonts.regular,
    fontSize: 13,
  },
  settingsDropdownOptionTextSelected: {
    color: theme.colors.accentText,
  },
  settingsNoResults: {
    color: theme.colors.textMuted,
    fontFamily: theme.fonts.regular,
    fontSize: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  settingsCard: {
    borderWidth: 1,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.bgRaised,
    borderRadius: 12,
    padding: 14,
    gap: 12,
  },
  settingsCardLabel: { color: theme.colors.textSecondary, fontSize: 11 },
  settingsHintLink: { color: theme.colors.brand, textDecorationLine: 'underline' },
  settingsKeyText: {
    color: theme.colors.textPrimary,
    fontSize: 11,
    lineHeight: 16,
    fontFamily: 'monospace',
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 8,
    backgroundColor: 'rgba(0,0,0,0.25)',
  },
  settingsCopyButton: {
    alignSelf: 'flex-start',
    borderWidth: 1,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.bgBase,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  settingsCopyButtonText: {
    color: theme.colors.textSecondary,
    fontSize: 12,
    fontWeight: '600',
  },
  settingsHintText: { color: theme.colors.textSecondary, fontSize: 11 },
  settingsActionButton: {
    alignSelf: 'flex-start',
    borderWidth: 1,
    borderColor: theme.colors.textSecondary,
    backgroundColor: theme.colors.bgBase,
    borderRadius: 12,
    paddingHorizontal: 18,
    paddingVertical: 12,
  },
  settingsActionButtonText: { color: theme.colors.textSecondary, fontSize: 13, fontWeight: '500' },
  settingsActionsRow: {
    marginTop: 4,
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  settingsSecondaryButton: {
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: 12,
    paddingHorizontal: 18,
    paddingVertical: 12,
    backgroundColor: 'transparent',
  },
  settingsSecondaryButtonText: { color: theme.colors.textSecondary, fontSize: 13 },
  button: {
    backgroundColor: theme.colors.brand,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    marginTop: 8,
    marginBottom: 10,
    minHeight: 36,
    flex: 1,
  },
  buttonText: { color: theme.colors.textLight, fontWeight: '700', fontSize: 13 },
  secondaryButton: {
    borderColor: theme.colors.border,
    borderWidth: 1,
    borderRadius: 6,
    paddingHorizontal: 7,
    paddingVertical: 5,
    minHeight: 24,
    justifyContent: 'center',
    backgroundColor: 'transparent',
  },
  secondaryButtonText: { color: theme.colors.textSecondary, fontSize: 11, fontWeight: '500' },
  deleteButton: {
    borderColor: 'transparent',
    borderWidth: 1,
    borderRadius: 6,
    paddingHorizontal: 7,
    paddingVertical: 5,
    minHeight: 24,
    justifyContent: 'center',
  },
  deleteButtonConfirm: {
    backgroundColor: 'rgba(220,60,60,0.15)',
    borderColor: 'rgba(220,60,60,0.3)',
  },
  deleteText: { color: theme.colors.textMuted, fontSize: 13, fontWeight: '500' },
  deleteTextConfirm: { color: theme.colors.danger },
  deleteIcon: { color: theme.colors.textMuted },
  swipeRow: {
    position: 'relative',
    marginBottom: 8,
    zIndex: 1,
    overflow: 'visible',
  },
  swipeRowRaised: {
    zIndex: 20,
    elevation: 20,
  },
  swipeActionWrap: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    width: SWIPE_ACTION_WIDTH,
    justifyContent: 'center',
    alignItems: 'stretch',
  },
  swipeDeleteAction: {
    flex: 1,
    backgroundColor: 'rgba(220,60,60,0.16)',
    borderColor: 'rgba(220,60,60,0.32)',
    borderWidth: 1,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  swipeDeleteText: { color: theme.colors.danger, fontSize: 12, fontWeight: '700' },
  swipeCardWrap: {
    zIndex: 2,
    overflow: 'visible',
  },
  card: {
    backgroundColor: theme.colors.bgSurface,
    borderColor: theme.colors.border,
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  listCell: { position: 'relative', zIndex: 1, overflow: 'visible' },
  listCellRaised: { position: 'relative', zIndex: 30, elevation: 30, overflow: 'visible' },
  entryOverlay: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: 'rgba(6, 10, 12, 0.6)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
    zIndex: 50,
  },
  entryPanel: {
    width: '100%',
    maxWidth: 560,
    maxHeight: '88%',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.bgSurface,
    padding: 16,
    gap: 10,
  },
  entryPanelTitle: { color: theme.colors.textPrimary, fontWeight: '700', fontSize: 16, flexShrink: 1 },
  entryPanelSummary: { color: theme.colors.textSecondary, fontSize: 12, flexShrink: 1 },
  entryPanelTags: { flexDirection: 'row', alignItems: 'center', gap: 6, flexWrap: 'wrap' },
  entryPanelBodyWrap: {
    flexShrink: 1,
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: 10,
    backgroundColor: theme.colors.bgRaised,
    maxHeight: '100%',
    overflow: 'hidden',
  },
  entryPanelBodyScroll: {
    maxHeight: '100%',
  },
  entryPanelBodyContent: {
    padding: 12,
  },
  markdownBody: { gap: 8 },
  markdownParagraph: { color: theme.colors.textPrimary, fontSize: 13, lineHeight: 20, flexShrink: 1 },
  markdownHeading: { fontWeight: '700' },
  markdownBold: { color: theme.colors.textPrimary, fontWeight: '700' },
  markdownUnderline: { color: theme.colors.textPrimary, textDecorationLine: 'underline' },
  markdownItalic: { color: theme.colors.textPrimary, fontStyle: 'italic' },
  markdownCode: { color: theme.colors.textPrimary, backgroundColor: 'rgba(255,255,255,0.07)' },
  markdownLink: { color: '#86b7ff', textDecorationLine: 'underline' },
  markdownCodeBlock: { borderRadius: 8, backgroundColor: 'rgba(0,0,0,0.25)', padding: 10, minWidth: 0 },
  markdownCodeScrollContent: { minWidth: '100%' },
  markdownCodeBlockText: { color: theme.colors.textPrimary, fontSize: 12, lineHeight: 18, fontFamily: theme.fonts.mono, flexShrink: 1 },
  markdownList: { gap: 4 },
  markdownListItem: { flexDirection: 'row', alignItems: 'flex-start', gap: 6 },
  markdownListBullet: { color: theme.colors.textSecondary, fontSize: 13, lineHeight: 20, minWidth: 14 },
  markdownQuote: { borderLeftWidth: 2, borderLeftColor: theme.colors.border, paddingLeft: 10 },
  markdownQuoteText: { color: theme.colors.textSecondary },
  markdownTableWrap: { marginVertical: 2 },
  markdownTable: { borderWidth: 1, borderColor: theme.colors.border, borderRadius: 8, overflow: 'hidden' },
  markdownTableRow: { flexDirection: 'row' },
  markdownTableHeaderRow: { backgroundColor: 'rgba(255,255,255,0.03)' },
  markdownTableCell: { borderRightWidth: 1, borderBottomWidth: 1, borderColor: theme.colors.border, paddingHorizontal: 8, paddingVertical: 6, minWidth: 92, flexShrink: 1 },
  markdownTableHeaderCell: { backgroundColor: 'rgba(255,255,255,0.02)' },
  markdownTableHeaderText: { fontWeight: '700' },
  markdownTableText: { color: theme.colors.textSecondary },
  conversationWrap: { gap: 10, minWidth: 0 },
  conversationRow: { width: '100%' },
  conversationRowHuman: { alignItems: 'flex-end' },
  conversationRowAssistant: { alignItems: 'flex-start' },
  conversationBubble: { maxWidth: '92%', minWidth: 0, borderRadius: 12, paddingVertical: 8, paddingHorizontal: 10, borderWidth: 1 },
  conversationBubbleHuman: { backgroundColor: 'rgba(29,158,117,0.18)', borderColor: 'rgba(29,158,117,0.38)' },
  conversationBubbleAssistant: { backgroundColor: 'rgba(255,255,255,0.03)', borderColor: theme.colors.border },
  conversationSender: { color: theme.colors.textMuted, fontSize: 10, lineHeight: 12, textTransform: 'uppercase', letterSpacing: 0.6, marginBottom: 3 },
  entryPanelActions: { flexDirection: 'row', justifyContent: 'flex-end' },
  cardTopRow: { flexDirection: 'row', gap: 10 },
  cardMainCol: { flex: 1, minWidth: 0 },
  cardActionCol: { alignItems: 'flex-end', gap: 8, flexShrink: 0 },
  cardActionRow: { flexDirection: 'row', gap: 6, flexWrap: 'nowrap', justifyContent: 'flex-end' },
  cardMetaRowMobile: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 8, marginBottom: 2 },
  cardMetaLead: { flexDirection: 'row', alignItems: 'flex-start', gap: 8, flex: 1, minWidth: 0 },
  mobileTitleActionRow: { flexDirection: 'row', alignItems: 'center', gap: 6, flexShrink: 0 },
  mobileActionDrawerWrap: { position: 'relative', alignItems: 'flex-end' },
  mobileActionTrigger: {
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: 8,
    minWidth: 30,
    minHeight: 28,
    paddingHorizontal: 8,
    paddingVertical: 4,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'transparent',
  },
  mobileActionTriggerText: { color: theme.colors.textSecondary, fontSize: 16, lineHeight: 18, fontWeight: '700' },
  mobileActionTriggerIcon: { color: theme.colors.textSecondary },
  mobileActionDrawer: {
    position: 'absolute',
    zIndex: 3,
    minWidth: 132,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.bgSurface,
    paddingVertical: 4,
  },
  mobileActionDrawerPortal: {
    zIndex: 90,
    elevation: 90,
  },
  mobileActionDrawerBackdrop: {
    flex: 1,
  },
  mobileActionDrawerItem: {
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  mobileActionDrawerText: { color: theme.colors.textPrimary, fontSize: 12, fontWeight: '500' },
  mobileActionDrawerDeleteText: { color: theme.colors.danger },
  cardMetaRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 8, marginBottom: 2 },
  cardIcon: { fontSize: 15, lineHeight: 15, marginTop: 1 },
  priorityText: { fontSize: 12, lineHeight: 12, fontWeight: '700', marginTop: 1 },
  tagPill: { borderRadius: 10, paddingHorizontal: 8, paddingVertical: 8 },
  tagPillText: { fontSize: 11, lineHeight: 14, fontWeight: '500' },
  cardTitle: { flexShrink: 1, color: theme.colors.textPrimary, fontWeight: '700', fontSize: 14, lineHeight: 19 },
  cardBody: { color: theme.colors.textSecondary, fontSize: 13, lineHeight: 20 },
  metaInfoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 6,
    marginBottom: 6,
  },
  reminderMetaPill: {
    backgroundColor: theme.colors.brandDim,
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  reminderMetaText: { color: theme.colors.brandText, fontSize: 11, lineHeight: 14 },
  metaDot: { color: theme.colors.textMuted, fontSize: 11 },
  metaText: { color: theme.colors.textMuted, fontSize: 11 },
  tagsRow: { flexDirection: 'row', alignItems: 'center', gap: 6, flexWrap: 'wrap' },
  itemTagPill: {
    backgroundColor: theme.colors.brandDim,
    borderRadius: 999,
    borderColor: theme.colors.border,
    borderWidth: 1,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  itemTagText: { color: theme.colors.brandText, fontSize: 11, lineHeight: 14 },
  error: {
    color: '#f87171',
    marginVertical: 6,
    backgroundColor: 'rgba(220,60,60,0.1)',
    borderWidth: 1,
    borderColor: 'rgba(220,60,60,0.25)',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    fontSize: 13,
  },
  editPanel: {
    width: '100%',
    maxWidth: 560,
    maxHeight: '88%',
    backgroundColor: theme.colors.bgSurface,
    borderColor: theme.colors.border,
    borderWidth: 1,
    borderRadius: 12,
  },
  editOverlay: {
    flex: 1,
    backgroundColor: 'rgba(6, 10, 12, 0.6)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
  },
  editScroll: { maxHeight: '100%' },
  editScrollContent: { padding: 12, gap: 2 },
  editTitle: { color: theme.colors.textPrimary, fontWeight: '600', fontSize: 14, marginBottom: 8 },
  editLabel: { color: theme.colors.textMuted, fontSize: 11, marginBottom: 4 },
  tagCountText: { color: theme.colors.textSecondary, fontSize: 10, marginBottom: 6, marginTop: 6, fontWeight: '500' },
  categoryRow: { flexDirection: 'row', flexWrap: 'nowrap', gap: 8, marginBottom: 8, paddingRight: 4 },
  editField: {
    backgroundColor: theme.colors.bgRaised,
    color: theme.colors.textPrimary,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: theme.colors.border,
    minHeight: 38,
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginBottom: 8,
    fontSize: 13,
  },
  editInputCompact: {
    backgroundColor: theme.colors.bgRaised,
    color: theme.colors.textPrimary,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: theme.colors.border,
    minHeight: 60,
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginBottom: 8,
    fontSize: 13,
    lineHeight: 19,
  },
  editInput: {
    backgroundColor: theme.colors.bgRaised,
    color: theme.colors.textPrimary,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: theme.colors.border,
    minHeight: 350,
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginBottom: 8,
    fontSize: 13,
    lineHeight: 19,
    textAlignVertical: 'top',
  },
  tagInputRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  tagInput: { flex: 1, marginBottom: 0 },
  editActionRow: { flexDirection: 'row', justifyContent: 'flex-end', gap: 8, marginTop: 10 },
  editSaveButton: {
    backgroundColor: theme.colors.brand,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 9,
    paddingHorizontal: 12,
    minHeight: 36,
  },
});

export default styles;
