import { StyleSheet } from 'react-native';
import { theme } from '../theme';
import { openBrainStyle } from '../constants/openbrainStyle';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.bgBase,
  },
  content: {
    flex: 1,
  },
  contentContainer: {
    padding: 16,
    paddingBottom: 120,
  },
  headerCard: {
    backgroundColor: theme.colors.bgSurface,
    borderColor: theme.colors.border,
    borderWidth: 1,
    borderRadius: 20,
    padding: 16,
    marginBottom: 12,
    flexDirection: 'row',
    gap: 12,
    alignItems: 'center',
    shadowColor: openBrainStyle.shadow,
    shadowOpacity: 0.24,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 10 },
  },
  avatarWrap: {
    width: 60,
    height: 60,
    borderRadius: 30,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  avatar: {
    width: '100%',
    height: '100%',
  },
  avatarFallback: {
    flex: 1,
    backgroundColor: openBrainStyle.avatarFallbackBg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarFallbackText: {
    color: openBrainStyle.accentText,
    fontFamily: 'sans-serif',
    fontSize: 24,
    fontWeight: '700',
  },
  headerTextWrap: {
    flex: 1,
    gap: 2,
  },
  sectionCard: {
    backgroundColor: theme.colors.bgSurface,
    borderColor: theme.colors.border,
    borderWidth: 1,
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    gap: 10,
    shadowColor: openBrainStyle.shadow,
    shadowOpacity: 0.22,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
  },
  sectionTitle: {
    color: theme.colors.textPrimary,
    fontFamily: openBrainStyle.fontSemiBold,
    fontSize: 16,
    marginBottom: 2,
  },
  eyebrow: {
    color: openBrainStyle.accent,
    fontFamily: openBrainStyle.fontSemiBold,
    fontSize: 11,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  title: {
    color: theme.colors.textPrimary,
    fontFamily: openBrainStyle.fontSerif,
    fontSize: 34,
    lineHeight: 38,
  },
  copy: {
    color: theme.colors.textSecondary,
    fontFamily: openBrainStyle.fontRegular,
    fontSize: 13,
  },
  label: {
    color: theme.colors.textPrimary,
    fontFamily: openBrainStyle.fontRegular,
    fontSize: 13,
  },
  fieldHint: {
    color: theme.colors.textMuted,
    fontFamily: openBrainStyle.fontRegular,
    fontSize: 12,
    marginTop: -2,
  },
  input: {
    backgroundColor: theme.colors.bgRaised,
    borderColor: theme.colors.border,
    borderWidth: 1,
    borderRadius: 10,
    color: theme.colors.textPrimary,
    fontFamily: openBrainStyle.fontRegular,
    fontSize: 14,
    paddingHorizontal: 12,
    paddingVertical: 11,
  },
  inputDisabled: {
    color: theme.colors.textMuted,
  },
  timezoneDropdown: {
    backgroundColor: theme.colors.bgRaised,
    borderColor: theme.colors.border,
    borderWidth: 1,
    borderRadius: 10,
    minHeight: 44,
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
  },
  timezoneDropdownWrapper: {
    position: 'relative',
    zIndex: 40,
  },
  timezoneDropdownText: {
    color: theme.colors.textPrimary,
    fontFamily: openBrainStyle.fontRegular,
    fontSize: 14,
  },
  timezoneDropdownChevron: {
    color: theme.colors.textSecondary,
    fontFamily: openBrainStyle.fontSemiBold,
    fontSize: 12,
  },
  timezoneDropdownList: {
    position: 'absolute',
    top: 48,
    left: 0,
    right: 0,
    backgroundColor: theme.colors.bgRaised,
    borderColor: theme.colors.border,
    borderWidth: 1,
    borderRadius: 10,
    maxHeight: 220,
    zIndex: 30,
    elevation: 8,
  },
  timezoneDropdownListContent: {
    paddingVertical: 4,
  },
  timezoneSearchInput: {
    backgroundColor: theme.colors.bgSurface,
    borderColor: theme.colors.border,
    borderWidth: 1,
    borderRadius: 8,
    color: theme.colors.textPrimary,
    fontFamily: openBrainStyle.fontRegular,
    fontSize: 13,
    marginHorizontal: 8,
    marginBottom: 4,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  timezoneDropdownOption: {
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  timezoneDropdownOptionSelected: {
    backgroundColor: openBrainStyle.accentDim,
  },
  timezoneDropdownOptionText: {
    color: theme.colors.textSecondary,
    fontFamily: openBrainStyle.fontRegular,
    fontSize: 13,
  },
  timezoneDropdownOptionTextSelected: {
    color: openBrainStyle.accentText,
  },
  timezoneNoResults: {
    color: theme.colors.textMuted,
    fontFamily: openBrainStyle.fontRegular,
    fontSize: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  primaryButton: {
    flex: 1,
    alignItems: 'center',
    backgroundColor: openBrainStyle.accentStrong,
    borderRadius: 10,
    paddingVertical: 11,
    paddingHorizontal: 14,
  },
  primaryButtonText: {
    color: openBrainStyle.accentOnSolid,
    fontFamily: openBrainStyle.fontSemiBold,
    fontSize: 14,
  },
  buttonDisabled: {
    backgroundColor: theme.colors.bgHover,
  },
  buttonDisabledText: {
    color: theme.colors.textMuted,
  },
  secondaryButton: {
    flex: 1,
    alignItems: 'center',
    backgroundColor: theme.colors.bgRaised,
    borderColor: theme.colors.border,
    borderWidth: 1,
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 14,
  },
  secondaryButtonText: {
    color: theme.colors.textSecondary,
    fontFamily: openBrainStyle.fontSemiBold,
    fontSize: 14,
  },
  muted: {
    color: theme.colors.textSecondary,
    fontFamily: openBrainStyle.fontRegular,
    fontSize: 14,
  },
  actionsRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 4,
  },
  error: {
    color: openBrainStyle.dangerStrong,
    backgroundColor: openBrainStyle.dangerBg,
    borderColor: openBrainStyle.dangerBorder,
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    fontFamily: openBrainStyle.fontRegular,
    fontSize: 12,
  },
  success: {
    color: openBrainStyle.accentText,
    backgroundColor: openBrainStyle.accentDim,
    borderColor: openBrainStyle.accentBorder,
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    fontFamily: openBrainStyle.fontRegular,
    fontSize: 12,
  },
});

export default styles;
