import { StyleSheet } from 'react-native';
import { theme } from '../theme';

const styles = StyleSheet.create({
  headerSection: {
    marginBottom: 2,
  },
  formScroll: {
    flex: 1,
  },
  formContentContainer: {
    paddingBottom: 120,
  },
  sectionCard: {
    backgroundColor: theme.colors.bgSurface,
    borderColor: theme.colors.border,
    borderWidth: 1,
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    gap: 10,
    shadowColor: theme.colors.shadow,
    shadowOpacity: 0.22,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
  },
  sectionCardElevated: {
    zIndex: 100,
    elevation: 12,
  },
  sectionTitle: {
    color: theme.colors.textPrimary,
    fontFamily: theme.fonts.semibold,
    fontSize: 16,
    marginBottom: 2,
  },
  label: {
    color: theme.colors.textPrimary,
    fontFamily: theme.fonts.regular,
    fontSize: 13,
  },
  bioLabel: {
    marginTop: 8,
  },
  fieldHint: {
    color: theme.colors.textMuted,
    fontFamily: theme.fonts.regular,
    fontSize: 12,
    marginTop: -2,
  },
  input: {
    backgroundColor: theme.colors.bgRaised,
    borderColor: theme.colors.border,
    borderWidth: 1,
    borderRadius: 10,
    color: theme.colors.textPrimary,
    fontFamily: theme.fonts.regular,
    fontSize: 14,
    paddingHorizontal: 12,
    paddingVertical: 11,
  },
  textArea: {
    minHeight: 96,
  },
  inputDisabled: {
    backgroundColor: theme.colors.bgBase,
    color: theme.colors.textMuted,
  },
  timezoneDropdown: {
    backgroundColor: theme.colors.bgRaised,
    borderColor: theme.colors.border,
    borderWidth: 1,
    borderRadius: 10,
    minHeight: 44,
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
  },
  timezoneDropdownWrapper: {
    position: 'relative',
    zIndex: 40,
  },
  timezoneDropdownText: {
    color: theme.colors.textPrimary,
    fontFamily: theme.fonts.regular,
    fontSize: 14,
  },
  timezoneDropdownChevron: {
    color: theme.colors.textSecondary,
    fontFamily: theme.fonts.semibold,
    fontSize: 12,
  },
  timezoneDropdownChevronIcon: {
    color: theme.colors.textSecondary,
  },
  timezoneDropdownList: {
    position: 'absolute',
    top: 48,
    left: 0,
    right: 0,
    backgroundColor: theme.colors.bgRaised,
    borderColor: theme.colors.border,
    borderWidth: 1,
    borderRadius: 10,
    maxHeight: 220,
    zIndex: 30,
    elevation: 8,
  },
  timezoneDropdownListContent: {
    paddingVertical: 4,
  },
  timezoneSearchInput: {
    backgroundColor: theme.colors.bgSurface,
    borderColor: theme.colors.border,
    borderWidth: 1,
    borderRadius: 8,
    color: theme.colors.textPrimary,
    fontFamily: theme.fonts.regular,
    fontSize: 13,
    marginHorizontal: 8,
    marginBottom: 4,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  timezoneDropdownOption: {
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  timezoneDropdownOptionSelected: {
    backgroundColor: theme.colors.accentDim,
  },
  timezoneDropdownOptionText: {
    color: theme.colors.textSecondary,
    fontFamily: theme.fonts.regular,
    fontSize: 13,
  },
  timezoneDropdownOptionTextSelected: {
    color: theme.colors.accentText,
  },
  timezoneNoResults: {
    color: theme.colors.textMuted,
    fontFamily: theme.fonts.regular,
    fontSize: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: theme.colors.accentStrong,
    borderRadius: 10,
    paddingVertical: 11,
    paddingHorizontal: 14,
    width: '100%',
  },
  primaryButtonText: {
    color: theme.colors.textLight,
    fontFamily: theme.fonts.semibold,
    fontSize: 14,
  },
  buttonDisabled: {
    backgroundColor: theme.colors.bgHover,
  },
  buttonDisabledText: {
    color: theme.colors.textMuted,
  },
  secondaryButton: {
    alignItems: 'center',
    backgroundColor: theme.colors.bgRaised,
    borderColor: theme.colors.border,
    borderWidth: 1,
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 14,
    width: '100%',
  },
  secondaryButtonText: {
    color: theme.colors.textSecondary,
    fontFamily: theme.fonts.semibold,
    fontSize: 14,
  },
  muted: {
    color: theme.colors.textSecondary,
    fontFamily: theme.fonts.regular,
    fontSize: 14,
  },
  actionsRow: {
    flexDirection: 'column',
    gap: 10,
    marginTop: 4,
    zIndex: 1,
  },
  error: {
    color: theme.colors.dangerStrong,
    backgroundColor: theme.colors.dangerBg,
    borderColor: theme.colors.dangerBorder,
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    fontFamily: theme.fonts.regular,
    fontSize: 12,
  },
  success: {
    color: theme.colors.accentText,
    backgroundColor: theme.colors.accentDim,
    borderColor: theme.colors.accentBorder,
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    fontFamily: theme.fonts.regular,
    fontSize: 12,
  },
});

export default styles;
