import { StyleSheet } from "react-native";
import { theme } from "../theme";
import {
  commonDropdownStyles,
  commonStatusStyles,
} from "../styles/commonStyles";

export const SWIPE_ACTION_WIDTH = 88;

const uppercaseLabel = {
  fontSize: 11,
  color: theme.colors.textMuted,
  letterSpacing: 0.66,
  textTransform: "uppercase",
  fontWeight: "500",
};

const entryActionMenuStyles = {
  mobileActionDrawerWrap: { position: "relative", alignItems: "flex-end" },
  mobileInlineActionsRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 6,
    width: "100%",
    marginBottom: 2,
    minHeight: 30,
    flexWrap: "wrap",
  },
  mobileActionTrigger: {
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: 8,
    minWidth: 30,
    minHeight: 30,
    paddingHorizontal: 8,
    paddingVertical: 4,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "transparent",
  },
  mobileActionTriggerText: {
    color: theme.colors.textSecondary,
    fontSize: 16,
    lineHeight: 18,
    fontWeight: "700",
  },
  mobileActionTriggerIcon: { color: theme.colors.textSecondary },
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.bgBase,
    paddingHorizontal: 12,
    paddingTop: 12,
    paddingBottom: 0,
  },
  contentArea: {
    flex: 1,
  },
  contentAreaBlurred: {
    opacity: 0.4,
  },
  row: { flexDirection: "row", gap: 8, marginBottom: 8 },
  statsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 12,
    width: "100%",
    justifyContent: "flex-start",
  },
  statsGridSmall: {
    flexWrap: "nowrap",
    gap: 8,
    justifyContent: "flex-start",
  },
  filterSection: { marginBottom: 8, position: "relative", zIndex: 1 },
  filterSectionOpen: {
    zIndex: 2,
  },
  filterDropdownDismissOverlay: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    zIndex: 1,
  },
  offlineBanner: {
    borderWidth: 1,
    borderColor: "#E5BC58",
    backgroundColor: "#F2EFE4",
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  offlineBannerWrap: {
    position: "relative",
    zIndex: 3,
    elevation: 8,
    gap: 8,
  },
  offlineBannerMessagePressable: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  offlineBannerDot: {
    width: 12,
    height: 12,
    borderRadius: 999,
    backgroundColor: "#E59E0C",
  },
  offlineBannerText: {
    color: "#9A4D12",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "500",
  },
  offlineBannerSyncButton: {
    borderWidth: 1,
    borderColor: "#E5BC58",
    backgroundColor: "#F4E9C5",
    borderRadius: 10,
    minWidth: 20,
    minHeight: 20,
    paddingHorizontal: 16,
    paddingVertical: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  offlineBannerSyncButtonDisabled: {
    opacity: 0.9,
  },
  offlineBannerSyncButtonText: {
    color: "#C8871A",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "700",
  },
  offlineBannerSyncGroup: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  offlineBannerSyncArrow: {
    color: "#C8871A",
    fontSize: 14,
    lineHeight: 16,
    fontWeight: "700",
  },
  clearFiltersButton: {
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.bgRaised,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 0,
  },
  clearFiltersButtonDisabled: { opacity: 0.6 },
  clearFiltersButtonText: {
    color: theme.colors.brandText,
    fontSize: 12,
    fontWeight: "600",
  },
  clearFiltersButtonTextDisabled: { color: theme.colors.textMuted },
  filterHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    zIndex: 2,
  },
  filterHeaderRowWithSpacing: { marginTop: 8, marginBottom: 8 },
  filterSearchRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    zIndex: 2,
  },
  filterSearchInputWrap: {
    flex: 1,
    minHeight: 40,
    borderWidth: 1,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.bgRaised,
    borderRadius: 14,
    paddingHorizontal: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  filterSearchIcon: { color: theme.colors.textMuted },
  filterDropdownContent: {
    backgroundColor: theme.colors.bgRaised,
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: 10,
    padding: 10,
    gap: 8,
  },
  filterDropdownContentOpen: {
    marginTop: -1,
    borderTopWidth: 0,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    zIndex: 2,
  },
  filterDropdownToggle: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: 1,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.bgRaised,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  filterDropdownToggleOpen: {
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
  },
  filterDropdownIconButton: {
    width: 40,
    height: 40,
    borderWidth: 1,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.bgRaised,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  filterDropdownIconButtonActive: {
    backgroundColor: theme.colors.brand,
    borderColor: theme.colors.brand,
  },
  filterDropdownIconButtonIcon: {
    color: theme.colors.textSecondary,
  },
  filterDropdownIconButtonIconActive: {
    color: theme.colors.textLight,
  },
  filterDropdownCountBadge: {
    position: "absolute",
    top: -4,
    right: -4,
    minWidth: 16,
    height: 16,
    borderRadius: 8,
    paddingHorizontal: 4,
    backgroundColor: theme.colors.textLight,
    borderWidth: 1,
    borderColor: theme.colors.brand,
    alignItems: "center",
    justifyContent: "center",
  },
  filterDropdownCountBadgeText: {
    color: theme.colors.brand,
    fontSize: 10,
    fontWeight: "700",
    lineHeight: 12,
  },
  filterDropdownChevron: {
    color: theme.colors.textMuted,
    fontSize: 10,
    fontWeight: "700",
  },
  filterDropdownChevronIcon: { color: theme.colors.textMuted },
  filterLabel: { ...uppercaseLabel },
  archivedToggle: { flexDirection: "row", alignItems: "center", gap: 8 },
  archivedToggleDropdown: {
    width: "100%",
    justifyContent: "space-between",
    backgroundColor: theme.colors.bgBase,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  archivedToggleText: { color: theme.colors.textSecondary, fontSize: 11 },
  filterRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 8,
  },
  filterRowLabel: { ...uppercaseLabel },
  filterSearchInput: {
    flex: 1,
    color: theme.colors.textPrimary,
    fontSize: 14,
    paddingVertical: 0,
    zIndex: 2,
  },
  filterStatusStackItem: {
    marginTop: 8,
  },
  creatingStatusList: {
    marginTop: 6,
    gap: 2,
  },
  creatingStatusText: {
    color: theme.colors.textMuted,
    fontSize: 12,
    lineHeight: 16,
  },
  editHelpText: {
    color: theme.colors.textSecondary,
    fontSize: 12,
    lineHeight: 16,
    marginBottom: 10,
  },
  queuedLoadingWrap: {
    minHeight: 120,
    alignItems: "center",
    justifyContent: "center",
  },
  queuedEntriesPanel: {
    borderWidth: 1,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.bgRaised,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 8,
  },
  queuedEntriesList: {
    gap: 8,
  },
  queuedEntriesTitle: {
    color: theme.colors.textSecondary,
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  queuedEntryCard: {
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: 8,
    backgroundColor: theme.colors.bgBase,
    paddingHorizontal: 10,
    paddingVertical: 8,
    gap: 6,
  },
  queuedEntryCardCompact: {
    gap: 4,
  },
  queuedEntryType: {
    color: theme.colors.textMuted,
    fontSize: 10,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  queuedEntrySummary: {
    color: theme.colors.textPrimary,
    fontSize: 12,
    lineHeight: 16,
  },
  queuedEntryMeta: {
    color: theme.colors.textMuted,
    fontSize: 10,
  },
  queuedEntryInput: {
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: 8,
    backgroundColor: theme.colors.bgSurface,
    color: theme.colors.textPrimary,
    paddingHorizontal: 10,
    paddingVertical: 8,
    minHeight: 50,
    fontSize: 12,
    lineHeight: 16,
    textAlignVertical: "top",
  },
  queuedEntryActionsRow: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 8,
  },
  queuedEntryButton: {
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: theme.colors.bgRaised,
    alignSelf: "flex-end",
  },
  queuedEntryButtonText: {
    color: theme.colors.textSecondary,
    fontSize: 11,
    fontWeight: "600",
  },
  queuedEntryError: {
    color: theme.colors.danger,
    fontSize: 11,
    lineHeight: 14,
  },
  pill: {
    borderWidth: 1,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.bgRaised,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  filterDropdownPill: {
    backgroundColor: theme.colors.bgSubtle,
    borderColor: theme.colors.borderSubtle,
  },
  pillActive: {
    borderColor: theme.colors.brand,
    backgroundColor: theme.colors.brand,
  },
  pillDisabled: { opacity: 0.55 },
  pillText: { fontSize: 11, color: theme.colors.textSecondary },
  pillTextActive: { color: theme.colors.textLight },
  pillTextDisabled: { color: theme.colors.textMuted },
  tagFilterPillContent: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  tagFilterCountBadge: {
    minWidth: 18,
    height: 18,
    borderRadius: 999,
    paddingHorizontal: 5,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: theme.colors.bgSurface,
  },
  tagFilterCountBadgeActive: {
    backgroundColor: "rgba(255,255,255,0.22)",
  },
  tagFilterCountBadgeDisabled: {
    backgroundColor: theme.colors.bgBase,
  },
  tagFilterCountText: {
    color: theme.colors.textMuted,
    fontSize: 10,
    fontWeight: "700",
    lineHeight: 11,
  },
  tagFilterCountTextActive: {
    color: theme.colors.textLight,
  },
  tagFilterCountTextDisabled: {
    color: theme.colors.textMuted,
  },
  statCard: {
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: 0,
    minWidth: 0,
    minHeight: 76,
    borderRadius: 14,
    borderWidth: 2,
    paddingVertical: 16,
    paddingHorizontal: 10,
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
  },
  statCardSmall: {
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: 0,
    minWidth: 0,
    minHeight: 68,
    paddingHorizontal: 7,
    paddingVertical: 10,
    borderRadius: 10,
    gap: 3,
  },
  statCardActive: {
    transform: [{ scale: 0.985 }],
    opacity: 0.92,
  },
  statSymbol: {
    fontSize: 15,
    lineHeight: 16,
    fontWeight: "700",
  },
  statCount: {
    fontSize: 24,
    lineHeight: 40,
    fontWeight: "800",
    textAlign: "center",
    includeFontPadding: false,
    flexShrink: 1,
  },
  statCount3Digits: {
    fontSize: 20,
    lineHeight: 30,
    letterSpacing: -0.3,
  },
  statCount4Digits: {
    fontSize: 16,
    lineHeight: 24,
    letterSpacing: -0.5,
  },
  statLabel: {
    fontSize: 7,
    lineHeight: 11,
    textTransform: "uppercase",
    letterSpacing: 1.25,
    fontWeight: "700",
  },
  statLabelSmall: {
    fontSize: 7,
    lineHeight: 10,
    letterSpacing: 0.8,
  },
  statLabelActive: { opacity: 0.95 },
  list: { flex: 1 },
  listContent: { paddingBottom: 84 },
  listContentEmpty: {
    flexGrow: 1,
  },
  listEmptyCentered: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  voiceCaptureOverlay: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    zIndex: 9,
    backgroundColor: "rgba(7, 11, 16, 0.18)",
    backdropFilter: "blur(4px)",
  },
  typebarDismissOverlay: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    zIndex: 8,
  },
  actionDrawerDismissOverlay: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    zIndex: 25,
  },
  listEmptyText: {
    color: theme.colors.textMuted,
    fontSize: 13,
    textAlign: "center",
    paddingTop: 24,
  },
  sectionHeaderText: {
    fontSize: 11,
    fontWeight: "500",
    color: theme.colors.textMuted,
    letterSpacing: 0.66,
    textTransform: "uppercase",
    marginBottom: 6,
    marginTop: 6,
  },
  typebarRow: {
    position: "absolute",
    left: 12,
    right: 12,
    bottom: 10,
    zIndex: 10,
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 10,
    backgroundColor: theme.colors.typebarSurface,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: theme.colors.border,
    padding: 6,
  },
  floatingMicWrap: {
    position: "absolute",
    right: 23,
    alignItems: "flex-end",
    zIndex: 10,
  },
  floatingMicButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "#F2F2F2",
    borderColor: "#D8DEE6",
    shadowColor: "#556172",
    shadowOpacity: 0.2,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 8,
  },
  floatingMicButtonIcon: {
    color: "#64748B",
  },
  micTooltipLeft: {
    right: 54,
    left: "auto",
    bottom: 10,
  },
  plusButtonWrap: {
    position: "absolute",
    right: 16,
    alignItems: "flex-end",
    zIndex: 10,
  },
  plusButton: {
    width: 62,
    height: 62,
    borderRadius: 31,
    borderWidth: 1,
    backgroundColor: theme.colors.brand,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: theme.colors.brand,
    shadowOpacity: 0.35,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 12,
  },
  plusButtonIcon: {
    color: "#F5F3FF",
  },
  typebarInput: {
    flex: 1,
    backgroundColor: theme.colors.bgRaised,
    color: theme.colors.textPrimary,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: theme.colors.border,
    minHeight: 38,
    paddingHorizontal: 16,
    paddingVertical: 8,
    fontSize: 13,
    lineHeight: 19,
  },
  typebarInputSmall: {
    paddingHorizontal: 12,
    fontSize: 11,
    lineHeight: 14,
  },
  typebarButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.brand,
    alignItems: "center",
    justifyContent: "center",
  },
  typebarUploadButton: {
    backgroundColor: theme.colors.bgRaised,
  },
  typebarActionWrap: {
    position: "relative",
    alignItems: "center",
  },
  typebarRecordingMeta: {
    position: "absolute",
    bottom: 42,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  micRecordingMetaLeft: {
    right: 54,
    left: "auto",
    bottom: 10,
  },
  typebarRecordingTimerBadge: {
    backgroundColor: "#111827",
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 5,
    minWidth: 76,
    alignItems: "center",
  },
  typebarRecordingTimer: {
    color: theme.colors.textLight,
    fontSize: 11,
    fontWeight: "600",
    flexShrink: 0,
  },
  typebarCancelRecordingButton: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.bgRaised,
    alignItems: "center",
    justifyContent: "center",
  },
  typebarCancelRecordingIcon: {
    color: theme.colors.danger,
  },
  typebarTooltip: {
    position: "absolute",
    bottom: 42,
    minWidth: 96,
    backgroundColor: "#111827",
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderWidth: 1,
    borderColor: theme.colors.border,
    zIndex: 20,
  },
  typebarTooltipText: {
    color: "#fff",
    fontSize: 11,
    fontWeight: "600",
    lineHeight: 14,
    flexShrink: 0,
    textAlign: "center",
  },
  typebarButtonDisabled: {
    backgroundColor: theme.colors.bgRaised,
  },
  typebarButtonText: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 16,
    lineHeight: 16,
  },
  typebarButtonIcon: { color: "#fff" },
  typebarButtonTextDisabled: { color: theme.colors.textMuted },
  typebarButtonIconDisabled: { color: theme.colors.textMuted },
  typebarUploadButtonText: { color: theme.colors.textSecondary, fontSize: 15 },
  typebarUploadButtonIcon: { color: theme.colors.textSecondary },
  settingsPanel: {
    width: "100%",
    maxWidth: 620,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.bgBase,
    padding: 16,
    gap: 12,
  },
  settingsScroll: { maxHeight: 560 },
  settingsScrollContent: { gap: 12 },
  settingsTitle: {
    color: theme.colors.textPrimary,
    fontSize: 18,
    fontWeight: "700",
  },
  settingsLabel: { color: theme.colors.textSecondary, fontSize: 11 },
  settingsInput: {
    borderWidth: 1,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.bgRaised,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: theme.colors.textPrimary,
    fontSize: 13,
  },
  settingsDropdown: {
    ...commonDropdownStyles.trigger,
  },
  settingsDropdownWrapper: {
    ...commonDropdownStyles.wrapper,
  },
  settingsDropdownText: {
    ...commonDropdownStyles.text,
  },
  settingsDropdownChevron: {
    ...commonDropdownStyles.chevronText,
  },
  settingsDropdownChevronIcon: { ...commonDropdownStyles.chevronIcon },
  settingsDropdownList: {
    ...commonDropdownStyles.list,
  },
  settingsDropdownListContent: { ...commonDropdownStyles.listContent },
  settingsDropdownSearchInput: {
    ...commonDropdownStyles.searchInput,
  },
  settingsDropdownOption: {
    ...commonDropdownStyles.option,
  },
  settingsDropdownOptionSelected: {
    ...commonDropdownStyles.optionSelected,
  },
  settingsDropdownOptionText: {
    ...commonDropdownStyles.optionText,
  },
  settingsDropdownOptionTextSelected: {
    ...commonDropdownStyles.optionTextSelected,
  },
  settingsNoResults: {
    ...commonDropdownStyles.noResults,
  },
  settingsCard: {
    borderWidth: 1,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.bgRaised,
    borderRadius: 12,
    padding: 14,
    gap: 12,
  },
  settingsCardLabel: { color: theme.colors.textSecondary, fontSize: 11 },
  settingsHintLink: {
    color: theme.colors.brand,
    textDecorationLine: "underline",
  },
  settingsKeyText: {
    color: theme.colors.textPrimary,
    fontSize: 11,
    lineHeight: 16,
    fontFamily: "monospace",
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 8,
    backgroundColor: "rgba(0,0,0,0.25)",
  },
  settingsCopyButton: {
    alignSelf: "flex-start",
    borderWidth: 1,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.bgBase,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  settingsCopyButtonText: {
    color: theme.colors.textSecondary,
    fontSize: 12,
    fontWeight: "600",
  },
  settingsHintText: { color: theme.colors.textSecondary, fontSize: 11 },
  settingsActionButton: {
    alignSelf: "flex-start",
    borderWidth: 1,
    borderColor: theme.colors.textSecondary,
    backgroundColor: theme.colors.bgBase,
    borderRadius: 12,
    paddingHorizontal: 18,
    paddingVertical: 12,
  },
  settingsActionButtonText: {
    color: theme.colors.textSecondary,
    fontSize: 13,
    fontWeight: "500",
  },
  settingsActionsRow: {
    marginTop: 4,
    flexDirection: "row",
    justifyContent: "flex-end",
  },
  settingsSecondaryButton: {
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: 12,
    paddingHorizontal: 18,
    paddingVertical: 12,
    backgroundColor: "transparent",
  },
  settingsSecondaryButtonText: {
    color: theme.colors.textSecondary,
    fontSize: 13,
  },
  settingsLogoutButtonText: {
    color: theme.colors.dangerStrong,
  },
  button: {
    backgroundColor: theme.colors.brand,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 10,
    marginTop: 8,
    marginBottom: 10,
    minHeight: 36,
    flex: 1,
  },
  buttonText: {
    color: theme.colors.textLight,
    fontWeight: "700",
    fontSize: 13,
  },
  secondaryButton: {
    borderColor: theme.colors.border,
    borderWidth: 1,
    borderRadius: 6,
    paddingHorizontal: 7,
    paddingVertical: 5,
    minHeight: 24,
    justifyContent: "center",
    backgroundColor: "transparent",
  },
  secondaryButtonText: {
    color: theme.colors.textSecondary,
    fontSize: 11,
    fontWeight: "500",
  },
  deleteButton: {
    borderColor: "transparent",
    borderWidth: 1,
    borderRadius: 6,
    paddingHorizontal: 7,
    paddingVertical: 5,
    minHeight: 24,
    justifyContent: "center",
  },
  deleteButtonConfirm: {
    backgroundColor: "rgba(220,60,60,0.15)",
    borderColor: "rgba(220,60,60,0.3)",
  },
  deleteText: {
    color: theme.colors.textMuted,
    fontSize: 13,
    fontWeight: "500",
  },
  deleteTextConfirm: { color: theme.colors.danger },
  deleteIcon: { color: theme.colors.textMuted },
  swipeRow: {
    position: "relative",
    marginVertical: 4,
    zIndex: 1,
    overflow: "visible",
  },
  swipeRowRaised: {
    zIndex: 20,
    elevation: 20,
  },
  swipeActionWrap: {
    position: "absolute",
    left: 0,
    top: 0,
    right: 0,
    bottom: 0,
    justifyContent: "center",
    alignItems: "flex-end",
    overflow: "hidden",
    backgroundColor: "rgba(220,60,60,0.16)",
    borderColor: "rgba(220,60,60,0.32)",
    borderWidth: 1,
    borderRadius: 10,
  },
  swipeDeleteAction: {
    height: "100%",
    width: SWIPE_ACTION_WIDTH,
    backgroundColor: "transparent",
    justifyContent: "center",
    alignItems: "center",
  },
  swipeDeleteText: {
    color: theme.colors.danger,
    fontSize: 12,
    fontWeight: "700",
  },
  swipeCardWrap: {
    zIndex: 2,
    overflow: "visible",
  },
  card: {
    backgroundColor: theme.colors.bgSurface,
    borderColor: theme.colors.border,
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: 12,
  },
  listCell: { position: "relative", zIndex: 1, overflow: "visible" },
  listCellRaised: {
    position: "relative",
    zIndex: 30,
    elevation: 30,
    overflow: "visible",
  },
  webEntryRow: { marginBottom: 10 },
  entryOverlay: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: "rgba(6, 10, 12, 0.6)",
    alignItems: "center",
    justifyContent: "center",
    padding: 16,
    zIndex: 50,
  },
  entryPanel: {
    width: "100%",
    maxWidth: 560,
    maxHeight: "88%",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.bgSurface,
    padding: 16,
    gap: 10,
  },
  entryDetailsPanelNoBackground: {
    backgroundColor: "transparent",
  },
  entryDetailsSubmenuHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border,
    paddingBottom: 8,
    marginBottom: 10,
  },
  entryDetailsSubmenuBackButton: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginLeft: 6,
    paddingVertical: 2,
  },
  entryDetailsSubmenuBackIcon: {
    color: theme.colors.textSecondary,
  },
  entryDetailsSubmenuLabel: {
    color: theme.colors.textMuted,
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: 0.66,
    fontWeight: "600",
  },
  entryPanelTitleRow: {
    position: "relative",
    zIndex: 30,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  entryPanelTitleRowLarge: {
    minHeight: 32,
  },
  entryPanelInlineActionsLarge: {
    width: "auto",
    marginBottom: 0,
    minHeight: 0,
    flexWrap: "nowrap",
    flexShrink: 0,
  },
  entryActionDismissOverlay: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    zIndex: 25,
  },
  entryPanelTitle: {
    color: theme.colors.textPrimary,
    fontWeight: "700",
    fontSize: 16,
    flex: 1,
    minWidth: 0,
  },
  entryPanelSummary: {
    color: theme.colors.textSecondary,
    fontSize: 12,
    flexShrink: 1,
  },
  entryCategoryMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  entryLastUpdatedText: {
    color: theme.colors.textMuted,
    fontSize: 11,
    textAlign: "right",
    flexShrink: 1,
  },
  entryPanelTags: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    flexWrap: "wrap",
  },
  entryPanelBodyWrap: {
    flexShrink: 1,
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: 10,
    backgroundColor: "transparent",
    maxHeight: "100%",
    overflow: "hidden",
  },
  entryPanelBodyScroll: {
    maxHeight: "100%",
  },
  entryPanelBodyContent: {
    paddingVertical: 12,
    paddingHorizontal: 0,
  },
  entryDetailsDividerToggle: {
    marginTop: 12,
    marginBottom: 8,
    paddingVertical: 8,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: theme.colors.border,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  entryDetailsDividerToggleText: {
    color: theme.colors.textSecondary,
    fontSize: 12,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  entryDetailsSummaryWrap: {
    paddingBottom: 8,
  },
  markdownBody: { gap: 8 },
  markdownParagraph: {
    color: theme.colors.textPrimary,
    fontSize: 13,
    lineHeight: 20,
    flexShrink: 1,
  },
  markdownHeading: { fontWeight: "700" },
  markdownBold: { color: theme.colors.textPrimary, fontWeight: "700" },
  markdownUnderline: {
    color: theme.colors.textPrimary,
    textDecorationLine: "underline",
  },
  markdownItalic: { color: theme.colors.textPrimary, fontStyle: "italic" },
  markdownCode: {
    color: theme.colors.textPrimary,
    backgroundColor: theme.colors.bgBase,
  },
  markdownLink: { color: "#86b7ff", textDecorationLine: "underline" },
  markdownCodeBlock: {
    borderRadius: 8,
    backgroundColor: theme.colors.bgSurface,
    padding: 10,
    minWidth: 0,
  },
  markdownCodeScrollContent: { minWidth: "100%" },
  markdownCodeBlockText: {
    color: theme.colors.textPrimary,
    fontSize: 12,
    lineHeight: 18,
    fontFamily: theme.fonts.mono,
    flexShrink: 1,
  },
  markdownList: { gap: 4 },
  markdownListItem: { flexDirection: "row", alignItems: "flex-start", gap: 6 },
  markdownListBullet: {
    color: theme.colors.textSecondary,
    fontSize: 13,
    lineHeight: 20,
    minWidth: 14,
  },
  markdownQuote: {
    borderLeftWidth: 2,
    borderLeftColor: theme.colors.border,
    paddingLeft: 10,
  },
  markdownQuoteText: { color: theme.colors.textSecondary },
  markdownTableWrap: { marginVertical: 2 },
  markdownTable: {
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: 8,
    overflow: "hidden",
  },
  markdownTableRow: { flexDirection: "row" },
  markdownTableHeaderRow: { backgroundColor: "rgba(255,255,255,0.03)" },
  markdownTableCell: {
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderColor: theme.colors.border,
    paddingHorizontal: 12,
    paddingVertical: 10,
    minWidth: 160,
    flexGrow: 1,
    flexShrink: 0,
    flexBasis: 0,
  },
  markdownTableHeaderCell: { backgroundColor: "rgba(255,255,255,0.02)" },
  markdownTableHeaderText: { fontWeight: "700" },
  markdownTableText: { color: theme.colors.textSecondary },
  conversationWrap: { gap: 10, minWidth: 0 },
  conversationRow: { width: "100%" },
  conversationRowHuman: { alignItems: "flex-end" },
  conversationRowAssistant: { alignItems: "flex-start" },
  conversationBubble: {
    maxWidth: "92%",
    minWidth: 0,
    borderRadius: 12,
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderWidth: 1,
  },
  conversationBubbleHuman: {
    backgroundColor: theme.colors.conversationBubbleHumanBg,
    borderColor: theme.colors.conversationBubbleHumanBorder,
  },
  conversationBubbleAssistant: {
    backgroundColor: theme.colors.bgSurface,
    borderColor: theme.colors.conversationBubbleAssistantBorder,
  },
  conversationSender: {
    color: theme.colors.textMuted,
    fontSize: 10,
    lineHeight: 12,
    textTransform: "uppercase",
    letterSpacing: 0.6,
    marginBottom: 3,
  },
  entryPanelActions: { flexDirection: "row", justifyContent: "flex-end" },
  cardTopRow: { flexDirection: "row", gap: 10 },
  cardMainCol: { flex: 1, minWidth: 0 },
  cardActionCol: { alignItems: "flex-end", gap: 8, flexShrink: 0 },
  cardActionRow: {
    flexDirection: "row",
    gap: 6,
    flexWrap: "nowrap",
    justifyContent: "flex-end",
  },
  cardMetaRowMobile: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    marginBottom: 2,
    minHeight: 30,
  },
  cardMetaLead: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flexShrink: 1,
    minHeight: 30,
  },
  mobileTitleActionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    flexShrink: 0,
    minHeight: 30,
  },
  ...entryActionMenuStyles,
  mobileActionDrawer: {
    position: "absolute",
    zIndex: 3,
    minWidth: 132,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.bgSurface,
    paddingVertical: 4,
  },
  mobileActionDrawerPortal: {
    zIndex: 90,
    elevation: 90,
  },
  mobileActionDrawerBackdrop: {
    flex: 1,
  },
  mobileActionDrawerItem: {
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  mobileActionDrawerText: {
    color: theme.colors.textPrimary,
    fontSize: 12,
    fontWeight: "500",
  },
  mobileActionDrawerDeleteText: { color: theme.colors.danger },
  cardMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 2,
    minHeight: 30,
  },
  cardIcon: { fontSize: 15, lineHeight: 15 },
  priorityText: { fontSize: 12, lineHeight: 14, fontWeight: "700" },
  tagPill: {
    borderRadius: 10,
    paddingHorizontal: 8,
    minHeight: 30,
    justifyContent: "center",
  },
  tagPillText: {
    fontSize: 11,
    lineHeight: 14,
    fontWeight: "500",
    textAlignVertical: "center",
  },
  cardTitle: {
    flexShrink: 1,
    color: theme.colors.textPrimary,
    fontWeight: "700",
    fontSize: 15,
    lineHeight: 21,
  },
  cardTitleBlock: {
    flex: 1,
    minHeight: 38,
    justifyContent: "center",
  },
  cardBody: {
    color: theme.colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
    marginTop: 4,
  },
  metaFooterRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    marginTop: 10,
    marginBottom: 4,
  },
  metaInfoRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    minWidth: 0,
    flexShrink: 1,
  },
  metaInfoCol: {
    minWidth: 0,
    flexShrink: 1,
    gap: 4,
  },
  reminderMetaPill: {
    backgroundColor: theme.colors.brandDim,
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  reminderMetaText: {
    color: theme.colors.brandText,
    fontSize: 11,
    lineHeight: 14,
  },
  metaText: { color: theme.colors.textMuted, fontSize: 11 },
  tagsRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    flexWrap: "nowrap",
    overflow: "hidden",
    justifyContent: "flex-end",
    flex: 1,
  },
  itemTagPill: {
    backgroundColor: theme.colors.bgSubtle,
    borderRadius: 999,
    borderColor: theme.colors.borderSubtle,
    borderWidth: 1,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  entryDetailsTagPill: {
    backgroundColor: theme.colors.bgSubtle,
    borderColor: theme.colors.borderSubtle,
    borderWidth: 1,
  },
  entryDetailsAddTagPill: {
    backgroundColor: "transparent",
    borderStyle: "dashed",
  },
  entryDetailsAddTagText: {
    color: theme.colors.textSecondary,
  },
  entryDetailsAddTagInputWrap: {
    width: "100%",
  },
  itemTagText: { color: theme.colors.textMuted, fontSize: 11, lineHeight: 14 },
  error: {
    ...commonStatusStyles.errorBanner,
    marginVertical: 0,
  },
  editPanel: {
    width: "100%",
    maxWidth: 560,
    maxHeight: "88%",
    backgroundColor: theme.colors.bgSurface,
    borderColor: theme.colors.border,
    borderWidth: 1,
    borderRadius: 12,
  },
  editOverlay: {
    flex: 1,
    backgroundColor: "rgba(6, 10, 12, 0.6)",
    alignItems: "center",
    justifyContent: "center",
    padding: 16,
  },
  editScroll: { flex: 1, maxHeight: "100%" },
  editScrollContent: { padding: 12, gap: 2 },
  queuedEditsEntriesScrollContent: { paddingBottom: 12 },
  editTitle: {
    color: theme.colors.textPrimary,
    fontWeight: "600",
    fontSize: 14,
    marginBottom: 8,
  },
  editLabel: { color: theme.colors.textMuted, fontSize: 11, marginBottom: 4 },
  editLabelRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  editLabelToggleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 4,
  },
  editToggleText: { color: theme.colors.textSecondary, fontSize: 11 },
  tagCountText: {
    color: theme.colors.textSecondary,
    fontSize: 10,
    marginBottom: 6,
    marginTop: 6,
    fontWeight: "500",
  },
  categoryRow: {
    flexDirection: "row",
    flexWrap: "nowrap",
    gap: 8,
    marginBottom: 8,
    paddingRight: 4,
  },
  editField: {
    backgroundColor: theme.colors.bgBase,
    color: theme.colors.textPrimary,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: theme.colors.border,
    minHeight: 38,
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginBottom: 8,
    fontSize: 13,
  },
  editInputCompact: {
    backgroundColor: theme.colors.bgBase,
    color: theme.colors.textPrimary,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: theme.colors.border,
    minHeight: 60,
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginBottom: 8,
    fontSize: 13,
    lineHeight: 19,
  },
  editInput: {
    backgroundColor: theme.colors.bgBase,
    color: theme.colors.textPrimary,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: theme.colors.border,
    minHeight: 350,
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginBottom: 8,
    fontSize: 13,
    lineHeight: 19,
    textAlignVertical: "top",
  },
  editInputDisabled: { opacity: 0.7 },
  editMarkdownPreview: {
    backgroundColor: theme.colors.bgBase,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: theme.colors.border,
    minHeight: 120,
    paddingHorizontal: 10,
    paddingVertical: 10,
    marginBottom: 8,
  },
  tagInputRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  tagInput: { flex: 1, marginBottom: 0 },
  editTagsRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    flexWrap: "wrap",
    justifyContent: "flex-start",
    marginBottom: 8,
  },
  editActionRow: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 8,
    marginTop: 10,
  },
  editSaveButton: {
    backgroundColor: theme.colors.brand,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 9,
    paddingHorizontal: 12,
    minHeight: 36,
  },
});

export default styles;
