import { StyleSheet } from "react-native";
import { theme } from "../theme";

const styles = StyleSheet.create({
  layoutBody: {
    paddingTop: 16,
  },
  heading: {
    color: "#0F172A",
    textAlign: "center",
    fontFamily: theme.fonts.semibold,
    fontSize: 24,
    lineHeight: 58,
    letterSpacing: -0.8,
  },
  description: {
    marginTop: 24,
    maxWidth: 460,
    color: "#8A99AD",
    textAlign: "center",
    fontFamily: theme.fonts.regular,
    fontSize: 16,
    lineHeight: 25,
  },
  saveAsNoteToggle: {
    backgroundColor: "transparent",
  },
  talkArea: { flex: 1, width: "100%" },
  container: { flex: 1 },
  messagesList: { flex: 1 },
  messagesWrap: { padding: 16, gap: 10, paddingBottom: 160, flexGrow: 1 },
  controlsWrap: {
    position: "absolute",
    left: 0,
    right: 0,
    alignItems: "center",
    width: "100%",
    justifyContent: "flex-start",
    paddingBottom: 20,
    zIndex: 20,
    elevation: 20,
  },
  micWrap: {
    marginTop: 44,
  },
  guidanceText: {
    marginTop: 14,
    paddingHorizontal: 16,
    marginHorizontal: 24,
    maxWidth: 440,
    color: theme.colors.text,
    fontFamily: theme.fonts.body,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "600",
    textAlign: "center",
    backgroundColor: theme.colors.bgRaised,
    borderRadius: 10,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  endButton: {
    marginTop: 14,
    minHeight: 40,
    minWidth: 120,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: theme.colors.bgRaised,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  endButtonDisabled: {
    opacity: 0.7,
  },
  endButtonText: {
    color: theme.colors.text,
    fontFamily: theme.fonts.body,
    fontWeight: "700",
    fontSize: 14,
    lineHeight: 18,
    textAlign: "center",
  },
  endButtonBusyWrap: {
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
    minHeight: 18,
  },
  endButtonBusyIndicator: {
    position: "absolute",
    left: 0,
  },
  finalizingWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    alignSelf: "flex-start",
    marginTop: 4,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: 10,
    backgroundColor: theme.colors.bgRaised,
  },
  finalizingText: {
    color: theme.colors.textSecondary,
    fontFamily: theme.fonts.body,
    fontSize: 13,
  },
  error: {
    color: theme.colors.danger,
    fontFamily: theme.fonts.body,
    marginHorizontal: 12,
    marginTop: 10,
    textAlign: "center",
  },
});

export default styles;
