import { StyleSheet } from "react-native";
import { theme } from "../theme";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F1F3F7",
    alignItems: "center",
  },
  topRow: {
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 20,
    minHeight: 56,
  },
  backButton: {
    position: "absolute",
    left: 20,
    width: 52,
    height: 52,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#D5DBE5",
    backgroundColor: "#F8FAFC",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#64748B",
    shadowOpacity: 0.18,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 8,
  },
  backIcon: {
    color: "#64748B",
  },
  title: {
    color: "#0F172A",
    fontFamily: theme.fonts.semibold,
    fontSize: 18,
    lineHeight: 24,
    letterSpacing: 0.1,
  },
  body: {
    flex: 1,
    width: "100%",
    alignItems: "center",
    paddingHorizontal: 24,
    paddingTop: 120,
  },
  heading: {
    color: "#0F172A",
    textAlign: "center",
    fontFamily: theme.fonts.semibold,
    fontSize: 24,
    lineHeight: 58,
    letterSpacing: -0.8,
  },
  subtitle: {
    marginTop: 24,
    maxWidth: 460,
    color: "#8A99AD",
    textAlign: "center",
    fontFamily: theme.fonts.regular,
    fontSize: 16,
    lineHeight: 25,
  },
  error: {
    marginTop: 10,
    color: "#DC2626",
    fontFamily: theme.fonts.regular,
    fontSize: 14,
    lineHeight: 20,
    textAlign: "center",
  },
  timer: {
    marginTop: 14,
    color: "#64748B",
    fontFamily: theme.fonts.semibold,
    fontSize: 14,
    lineHeight: 20,
    textAlign: "center",
  },
  micWrap: {
    marginTop: 44,
    alignItems: "center",
    justifyContent: "center",
    width: 244,
    height: 244,
  },
  micGlowOuter: {
    position: "absolute",
    width: 244,
    height: 244,
    borderRadius: 122,
    backgroundColor: theme.colors.brand,
    opacity: 0.16,
    transform: [{ scale: 1.08 }],
  },
  micGlowInner: {
    position: "absolute",
    width: 176,
    height: 176,
    borderRadius: 88,
    backgroundColor: theme.colors.brand,
    opacity: 0.24,
  },
  micButton: {
    width: 124,
    height: 124,
    borderRadius: 62,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: theme.colors.brand,
    shadowColor: theme.colors.brand,
    shadowOpacity: 0.34,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
    elevation: 14,
  },
  micButtonRecording: {
    backgroundColor: theme.colors.brand,
  },
  micButtonDisabled: {
    opacity: 0.6,
  },
  micIcon: {
    color: "#F8FAFC",
  },
});
